### ISSUE TITLE
how to login anonymously

### ISSUE THREAD

**Issue by jackielihf** [xmppjs/xmpp.js#125]
Hi all.

i want to login anonymously on web side, and chat to a customer service. 

i can not find how to do this using Class Client.

**Comment by mmmurf** [comment]
there is a documentation bug in node-xmpp-client where     preferredSaslMechanism: "ANONYMOUS"
 is shown as preferred: "ANONYMOUS" in the examples.

**Comment by lloydwatkin** [comment]
Thanks for pointing that out @mmmurf
