### ISSUE TITLE
Get entire stanza as an XML string?

### ISSUE THREAD

**Issue by baconmania** [xmppjs/xmpp.js#128]
If I prefer to use a different XML parsing mechanism than the one provided with node-xmpp, is it possible for me to just get the entire raw stanza within the client.on('stanza') callback as an XML string?

**Comment by shubham1164** [comment]
Can i convert string to xml inside xmpp.js lib so that I can send the converted xml stanza to xmpp.send(stringToXMLconvertedStanza)?

**Comment by sonnyp** [comment]
@shubham1164 

```js
const parse = require('@xmpp/xml/lib/parser')

xmpp.send(parse(`<presence/>`)
```

please open a new issue next time :)

**Comment by shubham1164** [comment]
Thanks @sonnyp. Sure.
