### ISSUE TITLE
Support TLSv1.1 and TLSv1.2

### ISSUE THREAD

**Issue by imaginator** [xmppjs/xmpp.js#192]
Connections fail when TLSv1 is disabled.

Testing (from http://prosody.im/doc/advanced_ssl_config#protocol)

Running prosody with:

```
ssl                    = {
                           key         = "...";
                           certificate = "..";
                           options     = {"no_sslv2", "no_sslv3", "no_tlsv1" };
                           }
```

fails.

Should really be trying to connect using TLSv1.2 and TLSv1.1

S.

**Comment by Rubensigner** [comment]
How do I solve this? -> TLS support is not compiled in
