### ISSUE TITLE
How do you compare to strophe.js

### ISSUE THREAD

**Issue by karellm** [xmppjs/xmpp.js#217]
Hi,

I'm starting a project that requires to develop a client side xmpp chat. I found `node-xmpp` and `strophe.js`. After some research, it is not perfectly clear which one I should pick.

Can you explain what the main differences are and which one is most suited for browser development?

Thanks a lot

**Comment by Robophil** [comment]
Thanks guys, reading down this thread has been educative. Which of this xmpp client would walk best for a nativescript project which is javascript based, yet has nothing to do with the dom directly.??
