### ISSUE TITLE
send a video/image file in xmpp

### ISSUE THREAD

**Issue by KeyideasGlobal** [xmppjs/xmpp.js#247]
Hi all,
   Plz somebody help me i am working on xmpp base chat application i want to send a video as well as image like other application how can i do this ihave a code which is sending image only as a file. is this also work for video ? and what is max size of video.

2nd things is how can i receive this and image/video and show this.

Thanks in Adv
Keyideas

**Comment by karanbalkar** [comment]
@lloydwatkin : The link is broken. Can you provide an updated link?

**Comment by lloydwatkin** [comment]
@sonnyp  ?

**Comment by sonnyp** [comment]
@lloydwatkin ?
