### ISSUE TITLE
Cannot load StringPrep-0.x.x bindings

### ISSUE THREAD

**Issue by Bugari** [xmppjs/xmpp.js#258]
When I try to use node-xmpp, I recieve warnings:

```
Cannot load StringPrep-0.5.4 bindings (using fallback). You may need to `npm install node-stringprep`
Cannot load StringPrep-0.6.1 bindings (using fallback). You may need to `npm install node-stringprep`
```

Problem seems to have two solutions, one is right on the log - install `node-stringprep`. Before I did this, there was only one line of log, after adding it, it has grown to two lines :cry: 

After reading about this lib, I added `apt-get install libicu-dev`, it did no good.

I'm using ubuntu-based distribution.

I know it's just the warning, but it really craps my unit tests, because they fail on warnings.

Is there a way it can be resolved?

**Comment by dreamersp** [comment]
+1 on this update.

**Comment by amrsobhy** [comment]
+1. 

For the time being, how do I install libicu 49.x?

**Comment by EricBorlandAC** [comment]
+1 On this... Btw is there anyway to silent the console.log of that at least? It is breaking my coverage.xml report...
