### ISSUE TITLE
better documentation and website

### ISSUE THREAD

**Issue by sonnyp** [xmppjs/xmpp.js#288]
Our current documentation is sparse.

It's mostly available in https://github.com/node-xmpp/node-xmpp.github.io but it definitely needs to be completed.

I'd prefer to have each repository contain its own documentation although I don't want to loose our website.

Ideally we would have each repo with its documentation and then build the website from the doc of each modules.

Any idea on the best tools to do that? I'd prefer Node.js stuff

**Comment by rikuhen** [comment]
+1

**Comment by lloydwatkin** [comment]
If we create gh-pages branches for each project then they should be availabe on `node-xmpp.org/$repo-name`

**Comment by lloydwatkin** [comment]
i.e. we can continue to use github's system for site pages and not have to roll our own.

**Comment by EternalDeiwos** [comment]
Any update here? I can't find any documentation on this at all...

**Comment by sonnyp** [comment]
@EternalDeiwos I'm working on it but on a rewrite at the same time so it may take a while. please checkout examples https://github.com/node-xmpp/node-xmpp/tree/master/packages for each packages and let me know if you have any questions meanwhile

**Comment by EternalDeiwos** [comment]
I managed to find another package that uses yours. Trying to set up a XMPP server to use with the new Firebase and Google stuff.

**Comment by sonnyp** [comment]
http://xmppjs.org/
