### ISSUE TITLE
Require TLS for server to server connections

### ISSUE THREAD

**Issue by chrisballinger** [xmppjs/xmpp.js#329]
There doesn't seem to be a way to prevent plaintext downgrade attacks by requiring TLS for all incoming and outgoing s2s connections.

**Comment by hyperlink** [comment]
could you provide more details on how this attack works?

**Comment by chrisballinger** [comment]
A man-in-the-middle removes the <starttls> elements from the initial plaintext server features, which can cause some clients to connect via plaintext instead. This affects both c2s and s2s connections, and should have separate options to both prevent the server from accepting incoming plaintext connections, and from preventing the client/server from downgrading outgoing connections to plaintext if the other server doesn't seem to offer starttls. Instead the connections should always fail if a secure channel cannot be established.

**Comment by sonnyp** [comment]
@chrisballinger interesting, feel free to send a PR.

**Comment by sonnyp** [comment]
node-xmpp is now deprecated
