### ISSUE TITLE
Does reconnect work on a BOSH connection?

### ISSUE THREAD

**Issue by shusak** [xmppjs/xmpp.js#350]
How does reconnect work on a client? 

I have the following setup:

```
    this.xmppClient = new XmppClient.Client({
      autostart: false,
      jid: userContext.jabberId,
      password: userContext.password,
      reconnect: true,
      bosh: {
          url: xmppBoshServerUrl
      }
    });
```

and if my connection is dropped (pull cable) and then put back, I'm getting an error from the server (404 Invalid Sid) and no reconnect is attempted.

The sequence I see is:

- Error is received
- Disconnect Event
- Offline Event
- Close Event 
- End Event

In what cases does reconnect happen?

**Comment by sonnyp** [comment]
Reconnect should work automatically, if it doesn't it's a bug.

**Comment by jeremy-j-ackso** [comment]
I'm running into reconnect problems as well. When I force halt and restart my vagrant VM running ejabberd, even with a very long `reconnect` option, the client just exits `0` after a couple seconds. Not even any additional `status` events emitted before it exits.

**Comment by HCodemesh** [comment]
Anybody found any work around on it?

**Comment by sonnyp** [comment]
node-xmpp is now deprecated
