### ISSUE TITLE
S2S Router

### ISSUE THREAD

**Issue by iclems** [xmppjs/xmpp.js#365]
Amazing project. I've been testing the S2S router with a public federation service (jwchat.org). Basic use case of router.js trying to send a message to somebody@jwchat.org

It appears the dial back never completes by default. 

It would simply stall after: 
```  xmpp:connection send: <db:verify to="jwchat.org" from="chat.nurves.com" id="8343268098092162682" type="valid"/> +0ms```

In DomainContext.prototype.verifyIncoming, switching the final "send" to outStream instead of inStream actually resolves the issue and enables to receive the final valid confirmation from the remote host. That seems strange though, no?

**Comment by iclems** [comment]
Sorry just noticed this is in the wrong package. Moving to the other side.

**Comment by sonnyp** [comment]
actually it moved here. There is an notice on the other repository. Maybe its time to close it.

**Comment by sonnyp** [comment]
node-xmpp is now deprecated
