### ISSUE TITLE
Intercept all incoming S2S stanzas

### ISSUE THREAD

**Issue by smokku** [xmppjs/xmpp.js#366]
I'd like a way to process all incoming S2S stanzas at central point, not having to `Router.register` every domain separately.

So far I do it by monkey-patching `DomainContext.prototype.receive`, but this is a brittle solution.

I would gladly code a PR, but first I would like to discuss a preferred solution.
I noticed _"Define and implement a simple/basic 'plugin' mechanism (catch in/out stanzas)"_ on [Roadmap](https://github.com/node-xmpp/node-xmpp/issues/293) - should this wait until this feature is implemented?

**Comment by sonnyp** [comment]
@smokku as you've seen `node-xmpp` is under a rewrite but to reduce the scope; at the moment only `client`, `component` and core libraries are concerned but if you're willing to work on `node-xmpp-server` rewrite I'd be happy to help.

The alternative is to maintain `node-xmpp-server` as it is.

**Comment by smokku** [comment]
I would gladly help. `node-xmpp-server` is not that big.

Any TODO? Pointers? Flow?

**Comment by sonnyp** [comment]
@smokku give me a couple of days to think about it and put everything in order

I tried to add you to my XMPP roster but didn't get a handshake yet, is your JID on your personal website up to date?

**Comment by smokku** [comment]
I am rarely online. Please try again. :)

**Comment by sonnyp** [comment]
node-xmpp is now deprecated
