### ISSUE TITLE
C2S/Session relies on urn:ietf:params:xml:ns:xmpp-session to bring user session online

### ISSUE THREAD

**Issue by smokku** [xmppjs/xmpp.js#367]
As of #364 :

> `<session xmlns="urn:ietf:params:xml:ns:xmpp-session"/>` has been removed from the spec, please refer to https://xmpp.org/rfcs/rfc6120.html rather than https://xmpp.org/rfcs/rfc3920.html

yet C2S/Session still relies on it to bring user session online.

See: https://github.com/node-xmpp/node-xmpp/blob/master/packages/node-xmpp-server/lib/C2S/Session.js#L159 and https://github.com/node-xmpp/node-xmpp/blob/master/packages/node-xmpp-server/lib/C2S/Session.js#L335

**Comment by sonnyp** [comment]
We should implement https://tools.ietf.org/html/draft-cridland-xmpp-session-01 which guarantees backward compatibility.

**Comment by sonnyp** [comment]
See https://github.com/node-xmpp/node-xmpp/pull/369 for `client`. Should fix your issue with `console`. But I'd leave this issue open as we should implement it server side as well.

**Comment by sonnyp** [comment]
node-xmpp is now deprecated
