### ISSUE TITLE
WebSocketServer emits Element not Stanza objects

### ISSUE THREAD

**Issue by smokku** [xmppjs/xmpp.js#390]
When creating `new xmpp.C2S.WebSocketServer()` and connecting `client.on('stanza', stanza => ...` on connection, function connected gets `Element` object, whereas in case of `new xmpp.C2S.TCPServer()` these are `Stanza` objects.

This makes it difficult to handle both C2S server types using the same internal logic. `Stanza` have helper properties as `stanza.type/from/to/id`, which Element does not - failing a code working with `Stanza`s in unexpected places.

**Comment by smokku** [comment]
I ended up with the following code:
```js
  this.server.on('connection', client => {
// ...
    client.on('stanza', stanza => {
      if (typeof stanza.type === 'undefined') {
        // C2S WebSocket connector passes ltx.Element not Stanza - reparse it
        stanza = xmpp.parse(stanza.toString())
      }
```

**Comment by sonnyp** [comment]
@smokku that's definitely a bug but I was thinking about deprecating `Stanza` anyway, it really doesn't add much. So I'd recommend against using helper properties.

**Comment by smokku** [comment]
This is one way of resolving this issue... ;-)

**Comment by sonnyp** [comment]
node-xmpp is now deprecated
