### ISSUE TITLE
server: Option to set additional stream features

### ISSUE THREAD

**Issue by smokku** [xmppjs/xmpp.js#391]
XMPP-IM and XEPs define that when server support non-mandatory features, these should be signalled as a stream feature. I have such feature implemented (`urn:xmpp:features:pre-approval`) and would like a way of adding it to stream-features of incoming streams.

**Comment by smokku** [comment]
So far I ended up with monkey-patching `Session` object:
```js
  session.sendFeatures = function () {
    if (this.authenticated) {
      const features = new xmpp.Element('stream:features', {
        xmlns: NS_STREAMS,
        'xmlns:stream': NS_STREAMS
      })
      features.c('bind', { xmlns: NS_BIND })
      features.c('session', { xmlns: NS_SESSION })
      for (let name of Object.keys(streamFeatures)) {
        features.c(name, { xmlns: streamFeatures[name] })
      }
      this.send(features)
    } else {
      this.constructor.prototype.sendFeatures.apply(this)
    }
  }
```

**Comment by sonnyp** [comment]
node-xmpp rewrite adds a mechanism to register custom stream features. `node-xmpp-server` won't be part of the initial rewrite release but we'll be able to reuse it.

**Comment by sonnyp** [comment]
node-xmpp is now deprecated
