### ISSUE TITLE
Document authoring plugins for node-xmpp-client

### ISSUE THREAD

**Issue by ggozad** [xmppjs/xmpp.js#397]
I am in the process of migrating a large codebase that was done on strophe to node-xmpp-client.
Some is proprietary some open-source for example https://github.com/ggozad/strophe.plugins 
Is there any documentation or examples on how to do this? I would be happy to write some but would appreciate at least examples.

**Comment by sonnyp** [comment]
`node-xmpp-client` doesn't have a plugin mechanism built-in altough it is pretty easy to implement yourself.

You should know `node-xmpp` is being rewritten and the new version (which should be ready/stable before the summer) supports plugins see https://github.com/node-xmpp/node-xmpp/tree/master/packages/plugins

**Comment by ggozad** [comment]
Are there any drafts or a branch that one should follow? Do you expect breakage with the client as it is now?

**Comment by sonnyp** [comment]
See https://github.com/node-xmpp/node-xmpp#rewrite

API will not be backward compatible with current `node-xmpp` API. It would be great if you could contribute those plugins to `node-xmpp` let me know if you're interested and how I can help you.

**Comment by ggozad** [comment]
I need to soon make a decision on which framework we will commit as a company. We are interested in the client part only at least for the time being (as in for the next year).
node-xmpp seems to be the choice, but it's hard to decide if there is no info on what changes are expected.
Things that would help would be:
1) A roadmap
2) an API for plugins. I actually found that Strophe's api was well designed and easy to use.

We could also talk about this things in person, perhaps this would make it easier than in a github ticket :)

**Comment by sonnyp** [comment]
@ggozad I'll drop you an email.
