### ISSUE TITLE
xmpp.js 0.2.0

### ISSUE THREAD

**Issue by sonnyp** [xmppjs/xmpp.js#434]
This issue track remaining tasks for the `xmpp.js` rename and `0.1.0` release

- [x] formalize API
- [x] documentation
  - [x] client
  - [x] component
  - [x] xml
- [x] xmppjs.org website

**Comment by smokku** [comment]
Regarding website, should we just use `xmpp.js.org` for free? See https://dns.js.org

**Comment by Sparshith** [comment]
Is the documentation elsewhere? :(

**Comment by sonnyp** [comment]
@Sparshith working on it.

@smokku I got `xmppjs.org` as https://dns.js.org doesn't allow for non web usage.

**Comment by smokku** [comment]
We could just ask nicely for SRV records.
( https://github.com/js-org/dns.js.org/issues/796 )

**Comment by sonnyp** [comment]
@smokku fair enough but I'm still concerned.

js.org seems to be a one man project and if anything goes wrong we loose our domain

for xmppjs.org I intend to give full administration of the domain to at least one trusted contributor

**Comment by sonnyp** [comment]
Just to clarify, for the website loosing the domain wouldn't be much trouble but for the XMPP server it's much more annoying.

**Comment by smokku** [comment]
Agreed.

It may be worth setting up xmpp.js.org -> xmppjs.org redirection though, to catch "typos".

**Comment by jonator** [comment]
Does this rewrite plan on supporting message archive management?
Will it be a plugin?
https://xmpp.org/extensions/xep-0313.html

**Comment by sonnyp** [comment]
EDIT: I'm not happy with the current plugin API for stanza routing and I don't want to cause too much troubles with a plugin API overhaul in the near future.

See https://github.com/node-xmpp/node-xmpp/issues/439

However I want to proceed with the release so I'm gonna release a 0.1.0 instead without non essential plugins. There is a `plugins` branch if you need them that will be kep in sync meanwhile if you need them.

**Comment by sonnyp** [comment]
xmpp.js 0.2.0 released

website online http://xmppjs.org/

project renamed
