### ISSUE TITLE
**online** event never called

### ISSUE THREAD

**Issue by Robophil** [xmppjs/xmpp.js#451]
When using `xmpp.js` to connect to `node-xmpp-server`, the **online** event on the server side is never called unlike when `node-xmpp-client` connects to the server which calls online on the server and the client itself. Why this behaviour?

**Comment by sonnyp** [comment]
That's because node-xmpp-server relies on a deprecated XMPP feature, session establishment.

node-xmpp-server is on a unmaintained state at this moment.

You can either fix node-xmpp-server to not rely on it or add a session establishment stream negotation plugin to xmpp.js.

https://tools.ietf.org/html/draft-cridland-xmpp-session-01

**Comment by Robophil** [comment]
Is there any available i could use at the moment? 
Also, is there any plans for further maintenance of **node-xmpp-server**

**Comment by sonnyp** [comment]
Try something like

```js
client.on('online', () => {
  this.plugins['iq-caller'].set(xml('session', {xmlns: NS}))
  .then(() => {
    console.log('session established');
  })
  .catch((err) => {
    console.error(err);
  })
})
```

I had a look to add this as a plugin but it doesn't really work as any other stream feature so it's pretty annoying and I probably won't.

Regarding node-xmpp-server I'd like to rewrite it as well some time in the future.

**Comment by Robophil** [comment]
Thanks, @sonnyp.
I'll close this for now. ;-)

**Comment by sonnyp** [comment]
@Robophil you're welcome hope it works for you.

As a side note, I recommend replacing node-xmpp-server with an XMPP server and a [xmpp.js component](http://xmppjs.org/component/) if you can.

**Comment by Robophil** [comment]
yh. I want to do that. I asked here in #450 but didn't get any response.
I started reviewing each component, but didn't see any or have the right idea of how to use the components to replace **node-xmpp-server**

**Comment by sonnyp** [comment]
@Robophil you didn't left me enough time to reply ;)

`@xmpp/client` works in Node.js and browsers

to use `@xmpp/component` with prosody take a look at 

* https://prosody.im/doc/components
* https://prosody.im/doc/configure#adding_componentsservices
* http://xmppjs.org/component/

example

* https://github.com/xmppjs/xmpp.js/blob/master/server/prosody.cfg.lua
* https://github.com/xmppjs/xmpp.js/blob/master/packages/component/example.js

**Comment by Robophil** [comment]
;-) my bad.

Thanks a lot.

**Comment by Robophil** [comment]
yay!!
I get it now. All is well in the world again ;-) Thanks @sonnyp
