### ISSUE TITLE
What happened to session-establishment ?

### ISSUE THREAD

**Issue by yurynix** [xmppjs/xmpp.js#454]
Hi,
What happened to the plugin `session-establishment` that was merged at PR #369 ?
It doesn't seems to be on `master`, so `xmpp.js` can't connect to  servers that require it.

currently I hack around it with:
```js
client.start( { uri: 'xmpp://xmpp.wordpress.com', domain: 'im.wordpress.com' } );
...
client.on('online', jid => {
    debug( 'online as ' + jid.toString() );

    client.sendReceive(
        xml( 'iq', { type: 'set', id: 'session_set' },
            xml( 'session', 'urn:ietf:params:xml:ns:xmpp-session' )
        )
    )
    .then( data => client.send( xml( 'presence', { 'xml:lang': 'en' } ) ) );
} );
```

**Comment by sonnyp** [comment]
See https://github.com/xmppjs/xmpp.js/issues/451#issuecomment-319209295

I didn't know there were still popular XMPP server out there requiring it.

Is it mandatory on `im.wordpress.com` ? If so I might reconsider.

**Comment by yurynix** [comment]
You can't connect with xmpp.js without the above hack to `im.wordpress.com`

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/pull/466
