### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dorklord23** [xmppjs/xmpp.js#455]
Hi :)

I've been spending some time studying this repo but I can't seem finding any documentation. Could someone pinpoint where is the documentation?

I'm sorry if this is a wrong place to ask for such a thing.

**Comment by sonnyp** [comment]
http://xmppjs.org/

**Comment by matepaiva** [comment]
@sonnyp, at xmpp.js there is documentation for client usage. What about node.js server usage? Or this lib does not meet this demand? Thank you!

**Comment by sonnyp** [comment]
The rewrite of server hasn't started yet. You can checkout deprecated node-xmpp-server though https://github.com/xmppjs/xmpp.js/tree/node-xmpp/packages/node-xmpp-server

Except from the examples, there's no documentation unfortunately.

**Comment by matepaiva** [comment]
Thank you for answering so fast. Is there any prediction about when it's going to be ready for production?

Also, I would like to understand more about why its under a rewrite, because, if it's possible, I would like to help in some way.
