### ISSUE TITLE
wrong Call of getMechanism in plugins/sasl/index.js

### ISSUE THREAD

**Issue by jjjb03** [xmppjs/xmpp.js#456]
call passes 4 arrays:
https://github.com/xmppjs/xmpp.js/blob/f52a3da7a912ad44e9f68a8e74247aa0b6a337f7/packages/plugins/sasl/index.js#L58-L61

function handles just the one:
https://github.com/xmppjs/xmpp.js/blob/f52a3da7a912ad44e9f68a8e74247aa0b6a337f7/packages/plugins/sasl/index.js#L86-L88
so - the 1st _offered_ method will be handled instead of the 1st _usable_ one

**Comment by NeoVance** [comment]
I use a plugin to get around this issue, you can obviously set up your own mechanism selection scheme in this way.

```
client.plugin({
  name: 'select-mechanism',
  plugin: (entity) => {
    const SASL = entity.plugin(require('@xmpp/plugins/sasl'));
    SASL.getMechanism = (offered, usable) => usable[0];
    return { entity };
  },
});
```

**Comment by sonnyp** [comment]
fixed in https://github.com/xmppjs/xmpp.js/pull/464
