### ISSUE TITLE
This was wildly hard to install with npm or yarn

### ISSUE THREAD

**Issue by brandonros** [xmppjs/xmpp.js#459]
Like, tragically

**Comment by sonnyp** [comment]
Okay, what's wrong?

**Comment by brandonros** [comment]
Try to install it with npm/yarn. I am pretty sure you guys made it private, so that isn't even possible?

Maybe include some instructions on the preferred way to install the package in the README or docs or somewhere?

**Comment by sonnyp** [comment]
I don't understand. What troubles did you run into?

Both `npm install @xmpp/client` and `yarn add @xmpp/client` appear to work fine.
