### ISSUE TITLE
Individual package pages return 404 in the docs

### ISSUE THREAD

**Issue by strugee** [xmppjs/xmpp.js#467]
AFAICT all of the links in http://xmppjs.org/packages/ 404.

**Comment by sonnyp** [comment]
thanks

I removed all links to `packages/*` http://xmppjs.org/client/

**Comment by strugee** [comment]
Are those docs not available anywhere else?

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/tree/master/docs
