### ISSUE TITLE
If the xmpp server is closed with the server component still connected, the process crashes after some time

### ISSUE THREAD

**Issue by satish-olx** [xmppjs/xmpp.js#481]
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:848:14)
```

**Comment by sonnyp** [comment]
thanks for the bug report

Can you tell us what server you use and how do you close it?

thanks

**Comment by satish-olx** [comment]
Hi,
Thanks for the quick prompt,
We are using ejabberd as the server, and we stop it. Whenever ejabberd is stopped it send the stream close stanza to all the clients. It gets closed successfully but the problem occurs after multiple retries to reconnect.

**Comment by sonnyp** [comment]
This should fix the issue https://github.com/xmppjs/xmpp.js/pull/514
