### ISSUE TITLE
node-xmpp-core package.json issue

### ISSUE THREAD

**Issue by wtolfday** [xmppjs/xmpp.js#484]
node-xmpp-core package.json uses a hard coded URL in its dependency 'reconnect-core' instead of a generic version number, as the following:
    "reconnect-core": "https://github.com/dodo/reconnect-core/tarball/merged",
This breaks npm install that uses a local npm registry. It forces the npm to go to GitHub.com instead of the local registry, which is blocked by the company's proxy. Noticed other dependencies are using version numbers except this one.

**Comment by sonnyp** [comment]
node-xmpp is deprecated in favor of xmpp.js

If you'd like this fixed I recommend you send a PR to the node-xmpp branch that adds reconnect-core as a file instead of an external dependency.
