### ISSUE TITLE
error xmpp with harmonyhub plugin

### ISSUE THREAD

**Issue by Nastra888** [xmppjs/xmpp.js#492]
Hello,

i get this error with a homebridge harmonyhub plugin, is this maybe a xmpp issue ?

Oct 14 03:39:23 Server homebridge[6836]: events.js:187
Oct 14 03:39:23 Server homebridge[6836]: throw err;
Oct 14 03:39:23 Server homebridge[6836]: ^
Oct 14 03:39:23 Server homebridge[6836]: Error: Unhandled "error" event. (XMPP authentication failure)
Oct 14 03:39:23 Server homebridge[6836]: at Client.emit (events.js:185:19)
Oct 14 03:39:23 Server homebridge[6836]: at Client._handleAuthState (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:298:10)
Oct 14 03:39:23 Server homebridge[6836]: at Client._handleStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:234:12)
Oct 14 03:39:23 Server homebridge[6836]: at Client.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:222:8)
Oct 14 03:39:23 Server homebridge[6836]: at emitOne (events.js:115:13)
Oct 14 03:39:23 Server homebridge[6836]: at Connection.emit (events.js:210:7)
Oct 14 03:39:23 Server homebridge[6836]: at Connection.onStanza (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:369:10)
Oct 14 03:39:23 Server homebridge[6836]: at StreamParser. (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)
Oct 14 03:39:23 Server homebridge[6836]: at emitOne (events.js:115:13)
Oct 14 03:39:23 Server homebridge[6836]: at StreamParser.emit (events.js:210:7)
Oct 14 03:39:23 Server homebridge[6836]: at SaxLtx. (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
Oct 14 03:39:23 Server homebridge[6836]: at emitOne (events.js:115:13)
Oct 14 03:39:23 Server homebridge[6836]: at SaxLtx.emit (events.js:210:7)
Oct 14 03:39:23 Server homebridge[6836]: at SaxLtx._handleTagOpening (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:28:22)
Oct 14 03:39:23 Server homebridge[6836]: at SaxLtx.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
Oct 14 03:39:23 Server homebridge[6836]: at StreamParser.write (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
Oct 14 03:39:23 Server homebridge[6836]: at Connection.onData (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)
Oct 14 03:39:23 Server homebridge[6836]: at emitOne (events.js:120:20)
Oct 14 03:39:23 Server homebridge[6836]: at Socket.emit (events.js:210:7)
Oct 14 03:39:23 Server homebridge[6836]: at addChunk (_stream_readable.js:266:12)
Oct 14 03:39:23 Server homebridge[6836]: at readableAddChunk (_stream_readable.js:253:11)
Oct 14 03:39:23 Server homebridge[6836]: at Socket.Readable.push (_stream_readable.js:211:10)
Oct 14 03:39:23 Server homebridge[6836]: at TCP.onread (net.js:585:20)
Oct 14 03:39:23 Server systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Oct 14 03:39:23 Server systemd[1]: homebridge.service: Unit entered failed state.
Oct 14 03:39:23 Server systemd[1]: homebridge.service: Failed with result 'exit-code'.
Oct 14 03:39:33 Server systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.

**Comment by sonnyp** [comment]
`XMPP authentication failure` means the user or password is not good.
