### ISSUE TITLE
SRV resolving issues

### ISSUE THREAD

**Issue by agnauck** [xmppjs/xmpp.js#498]
I am trying to the Client package to connect to a server which requires to lookup the host in the SRV records ( _xmpp-client._tcp.mydomain.com)

I try to connect like this:
`client.start('mydomain.com')`

which gives me this error:
`(node:9240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: querySrv ENODATA _xmpps-client._tcp.mydomain.com`

It looks like xmpp.js is trying to lookup xmpps SRV records, after it fails it does not proceed with xmpp records.

Records for _xmpps-client._tcp.mydomain.com do not exist for this domain, only _xmpp-client._tcp.mydomain.com records

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/pull/775/files#diff-86f802a2813c0b1e07e93fbb7e6d186f

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/releases/tag/v0.8.0
