### ISSUE TITLE
iq-caller page on docusite stays blank

### ISSUE THREAD

**Issue by TheNewCivilian** [xmppjs/xmpp.js#512]
I know this issue may not belong here, but couldn't find better place.
When I open [the documentation](http://xmppjs.org/plugins/iq-caller/) I only get blank pages in Firefox/Chrome. Should there be anything or isn't there a description for how to use iq's?

**Comment by viglucci** [comment]
Same problem. Is quite frustrating when examples are minimal or completely blank.

**Comment by bwcgn** [comment]
Here you go, just browse the repo

https://github.com/xmppjs/xmpp.js/tree/master/packages/plugins/iq-caller

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/tree/master/packages/iq
