### ISSUE TITLE
Docs clarification request: npm install what?

### ISSUE THREAD

**Issue by lacivert** [xmppjs/xmpp.js#521]
I see on it on https://www.npmjs.com/package/node-xmpp-client clearly stated as 

`npm install node-xmpp-client`

But there is no clarification either on here (Github Readme) or on website (xmppjs.org)

And as the repository names are changed and some of the names look deprecated as well, it may be misunderstood about names for npm install.

I think that should be pointed out clearly in website:

`npm install node-xmpp-client`

**Comment by sonnyp** [comment]
node-xmpp-client is deprecated

See
http://xmppjs.org/client/

`npm install @xmpp/client`

You're right it's unclear, specially because scoped packages aren't very common yet.

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js
