### ISSUE TITLE
BOSH connection?

### ISSUE THREAD

**Issue by lacivert** [xmppjs/xmpp.js#523]
Is it still in TODO or the client is ready for a bosh connection? If ready, how can we do that? Can you put a simple example/code block for it?

**Comment by sonnyp** [comment]
BOSH is not implemented but I'm still interested in adding support for it.

Out of curiosity, why do you need BOSH?

**Comment by lacivert** [comment]
Need to implement some 3rd party application for a BOSH server of a big company solution

**Comment by jbrodley** [comment]
+1 on BOSH support. Hipchat now only supports BOSH for access in the latest Datacenter editions (3.1.x).  This kills our ability to use things like Hubot that rely on the xmpp client.

**Comment by sonnyp** [comment]
duplicate https://github.com/xmppjs/xmpp.js/issues/561
