### ISSUE TITLE
Sending XML with Factory

### ISSUE THREAD

**Issue by ctur** [xmppjs/xmpp.js#529]
Im able to connect my  local ejabberd server but what i don't understand is how to send message which created using Factory method described in the Docs.

**Comment by sonnyp** [comment]
```javascript
client.send(
  xml('message', {type: 'chat'},
    xml('body', {}, 'hello world')
  )
)
```

https://github.com/xmppjs/xmpp.js/blob/master/packages/client/example/index.js#L49

does that answer your question?

**Comment by ctur** [comment]
Thanks a lot @sonnyp , it worked. How can i display received message on CLI?

**Comment by sonnyp** [comment]
```javascript
client.on('stanza', stanza => {
  console.log(stanza.toString())
})
```

**Comment by ctur** [comment]
@sonnyp Sonny is it possible to create voice chat - video chat with this library currently ? or can you point me out what to check maybe ?
