### ISSUE TITLE
Giving custom "Resource" on JID

### ISSUE THREAD

**Issue by ctur** [xmppjs/xmpp.js#530]
When connecting user it gives random Resouce on JID how to give initial Resource or change current Resource after connected to the server?

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/blob/master/packages/client/example/index.js#L72

```js
client.handle('bind', bind => {
    return bind('resource')
})
```

XMPP doesn't allow changing the resource after being connected so if you want to do that you'll have to reconnect.

**Comment by ctur** [comment]
Thanks for fast responses.
