### ISSUE TITLE
Creating Account through Client

### ISSUE THREAD

**Issue by ctur** [xmppjs/xmpp.js#534]
How could i create an account(JID and Password) through my Node.js client on ejabberd server  running on local?

**Comment by sonnyp** [comment]
Hello,

we don't implement in-band registration https://xmpp.org/extensions/xep-0077.html yet but that should be fairly easy if you want to give it a try.

**Comment by sonnyp** [comment]
see https://github.com/xmppjs/xmpp.js/issues/783
