### ISSUE TITLE
StartTls on Custom Socket

### ISSUE THREAD

**Issue by Robbilie** [xmppjs/xmpp.js#535]
ok so i wrote a custom transport implementing a socks5 proxy. this is kinda hacky but works, involves a wrapper around a socket. now if i want to use starttls on that, the check breaks obviously:

current npm version:
https://github.com/xmppjs/xmpp.js/blob/v0.3.0/packages/plugins/starttls/index.js#L15-L20
current master:
https://github.com/xmppjs/xmpp.js/blob/master/packages/starttls/index.js#L38-L46

is there a chance to invert this check for websocket and allow all others?

**Comment by Robbilie** [comment]
possibly an instanceof check would work but i guess the websocket socket is also a net.socket child class…?

**Comment by sonnyp** [comment]
It shouldn't be a problem anymore, the check was removed
