### ISSUE TITLE
clustering / redundancy - more then one XMPP server

### ISSUE THREAD

**Issue by syberkitten** [xmppjs/xmpp.js#537]
Hi
I'm looking into the javascript implementation of XMPP
compared to products like OpenFire / Ejabbered etc.

Didn't see any mentioning of clustering/redundancy,
are there any plans to support it in future or is it beyond the scope
of this project?

**Comment by sonnyp** [comment]
We don't have server libraries and we won't for the foreseeable future.

As a client, there's nothing specific to do to connect to a cluster.
