### ISSUE TITLE
Is stream management (XEP-0198) supported on the client?

### ISSUE THREAD

**Issue by jsrhome** [xmppjs/xmpp.js#540]
In an answer to issue #395, it was indicated that stream management (XEP-0198) would be available.  Did this make it into a release?  I don't see any code in the repository, and our ejabberd server requires it.

Thanks.

**Comment by sonnyp** [comment]
@jsrhome not yet. No ETA.

**Comment by jsrhome** [comment]
Okay.  Thanks for the reply.  I will close this issue.

**Comment by shubham1164** [comment]
Hi @jsrhome , do you have any plan to work on XEP-0198 in the near future? If not, can you guide some alternative way of achieving it for the time sake you implement it?

**Comment by jsrhome** [comment]
We switched to using stanza.io, which has stream management support.  While
xmpp.js is more modern in style (and easier to learn), we found that
stanza.io has more of the features we needed for our project.
