### ISSUE TITLE
EventEmitter: listenerCount returns 'undefined'

### ISSUE THREAD

**Issue by soulfly** [xmppjs/xmpp.js#549]
I have the following code:

```
var inputL = function(str) {
    console.log("input", str);
}

self.xmppClient.on('input', inputL);

console.log("Input listeners:", self.xmppClient.listenerCount('input'));
```

It prints 'undefined'

I did some investigations and found a root cause:

This is because there is no 'return' statement in this line 
https://github.com/xmppjs/xmpp.js/blob/master/packages/events/lib/EventEmitter.js#L41

so it should be like this:

` return this._emitter[name](...args)`

**Comment by sonnyp** [comment]
Hello,

Thanks for digging, I'll make a fix and add tests

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/pull/565
