### ISSUE TITLE
(Ask) How to parse roster from result

### ISSUE THREAD

**Issue by mafaza86** [xmppjs/xmpp.js#550]
I'm new to using xmpp.js, very nice and helpful, thanks to the contributors. but i want to ask about parse xml in stanza.

How to parse, get item nurse@example.com  and romeo@example.net

client send :
`<iq from='juliet@example.com/balcony'
       id='bv1bs71f'
       type='get'>
    <query xmlns='jabber:iq:roster'/>
  </iq>`

response server :
`<iq id='bv1bs71f'
       to='juliet@example.com/chamber'
       type='result'>
    <query xmlns='jabber:iq:roster' ver='ver7'>
      <item jid='nurse@example.com'/>
      <item jid='romeo@example.net'/>
    </query>
  </iq>`

**Comment by sonnyp** [comment]
see http://xmppjs.org/xml/

depends how you get the response but typically

```js
stanza.getChild('query', 'jabber:iq:roster').getChildren('item').map(child => child.attrs.jid)
```

will return an array of all jids

You can also use the roster plugin https://github.com/xmppjs/xmpp.js/tree/master/packages/plugins/roster

**Comment by nstod** [comment]
The roster plugin doesn't appear to be included in the latest npm packages.  Am I missing something?  Thanks!

**Comment by sonnyp** [comment]
roster package has been removed for the time being
