### ISSUE TITLE
Cannot find module "@xmpp/plugins/roster"

### ISSUE THREAD

**Issue by trabek** [xmppjs/xmpp.js#566]
I did as the README in roster package says:
`npm install @xmpp/plugins`
`const roster = client.plugin(require('@xmpp/plugins/roster'))`

and I got:
`Cannot find module "@xmpp/plugins/roster"`

And indeed there is no roster directory in `node_modules/@xmpp/plugins/`

**Comment by sonnyp** [comment]
roster package has been removed for the time being
