### ISSUE TITLE
Documentation: Example of looping through a list of endpoints

### ISSUE THREAD

**Issue by jeremy-j-ackso** [xmppjs/xmpp.js#568]
The documentation suggests that `With appropriate configuration it will even loop through a list of endpoints.`

Can we get an example of how added to the documentation? I'm not finding an obvious way to do this...

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/tree/master/packages/resolve#references

Some documentation would be great though

**Comment by sonnyp** [comment]
If you have correct server/dns configuration then there is nothing to do. xmpp.js handles it by itself.

- [RFC 6120 Resolution of Fully Qualified Domain Names](https://xmpp.org/rfcs/rfc6120.html#tcp-resolution)
- [XEP-0156: Discovering Alternative XMPP Connection Methods](https://xmpp.org/extensions/xep-0156.html)
- [XEP-0368: SRV records for XMPP over TLS](https://xmpp.org/extensions/xep-0368.html)
- [RFC 6415 Web Host Metadata](https://tools.ietf.org/html/rfc6415)
- [DNS configuration in Jabber/XMPP](https://prosody.im/doc/dns)
- [https://wiki.xmpp.org/web/SRV_Records](https://wiki.xmpp.org/web/SRV_Records)

**Comment by jeremy-j-ackso** [comment]
When I read `With appropriate configuration it will even loop through a list of endpoints` in the README I take that to mean that with appropriate _code_ configuration it could be done, and that it's a feature of **this library**.

If it's not a feature of the library, it probably shouldn't be in the README in a way that would lead someone to believe that it is.

**Comment by sonnyp** [comment]
I agree that the documentation should be improved there but it is implemented in the library itself by https://github.com/xmppjs/xmpp.js/tree/master/packages/resolve .

**Comment by sonnyp** [comment]
Specifically https://github.com/xmppjs/xmpp.js/blob/master/packages/resolve/index.js#L30

**Comment by jeremy-j-ackso** [comment]
I was expecting that a user would be able to pass multiple service URI's to the client. Manually configuring `@xmpp/resolve` doesn't really fulfill what's being claimed in the README about how easy and low-code it ought to be to loop through endpoints, especially if I'm a user that doesn't have admin capabilities to update DNS on our XMPP servers, and admins who do are reluctant to do so because of pre-existing network dependencies.
https://github.com/xmppjs/xmpp.js/tree/master/packages/client

**Comment by jeremy-j-ackso** [comment]
Heck, maybe even a one to two sentence description of each of the modules in the top-level README would help alleviate a lot of documentation problems here.

**Comment by sonnyp** [comment]
> I get that some of these are problems specific to my case, but it would be generally more useful and friendly to be able to add them when setting up the client. That way you only have to depend on @xmpp/client, and not several other sub-packages.

Ok just for clarification, `@xmpp/client` will loop through http/dns endpoints without any additional package (`@xmpp/resolve` is included in `@xmp/client`).

> Heck, maybe even a one to two sentence description of each of the modules in the top-level README would help alleviate a lot of documentation problems here.

Yep, that's mostly done, `resolve` is just a bad example. I'll see what I can do.

> I was expecting that a user would be able to pass multiple service URI's to the client

I strongly recommend to use DNS/HTTP standard lookups. However if that's really not an option, adding support for multiple endpoints *client side* in `xmpp.js` should be trivial.

What is your exact use case? fallback?
