### ISSUE TITLE
ReactNative: unable to resolve module `events`

### ISSUE THREAD

**Issue by DaveLombardo** [xmppjs/xmpp.js#571]
Hi there
I'm trying to use the latest 0.5.0 version but facing an issue:

Unable to resolve module `events` from `.../node_modules/@xmpp/reconnect/index.js`: Module `events` does not exist in the Haste module map

Looks like it comes from here
https://github.com/xmppjs/xmpp.js/blob/master/packages/reconnect/index.js#L3

just an idea: 
should it be like
`const EventEmitter = require('@xmpp/events')` instead of `const EventEmitter = require('events')`

**Comment by DaveLombardo** [comment]
I fixed it by installing `npm install events --save`

Is it a right solution?

**Comment by sonnyp** [comment]
Fixed in 0.5.1 https://github.com/xmppjs/xmpp.js/releases/tag/v0.5.1
