### ISSUE TITLE
ReactNative: unable to resolve module `tls` 

### ISSUE THREAD

**Issue by DaveLombardo** [xmppjs/xmpp.js#572]
Hi there
I'm trying to use the latest 0.5.0 version but facing an issue:

Unable to resolve module events from .../node_modules/@xmpp/starttls/client.js: Module 'tls' does not exist in the Haste module map

any ideas on how to make it workable under React Native?

FYI, currently I use 0.3.0 and do not have such issues, 
probably something changed with the imports

**Comment by ukaric** [comment]
@DaveLombardo I can confirm `@xmpp/client` version `^0.5.0` throws `tls` error.

**Comment by ukaric** [comment]
Running `yarn add tls` inside `@xmpp/starttls` resolves the issue.

**Comment by sonnyp** [comment]
Fixed in 0.5.1 https://github.com/xmppjs/xmpp.js/releases/tag/v0.5.1
