### ISSUE TITLE
Client : Attempting to connect to server but status "offline"

### ISSUE THREAD

**Issue by mwmouawad** [xmppjs/xmpp.js#574]
Hi currently I am testing out the client and  I am running an ejabberd server locally. 
The server is running fine, I've tested with Adium. But when I am trying to use the client library to connect I get multiple: 
"Accepted connection" simultaneously.
This is a screenshot of my local ejabberd server locally when I attempt to connect with the client library.
<img width="728" alt="capture d ecran 2018-10-14 a 23 16 39" src="https://user-images.githubusercontent.com/38508222/46922309-44a7db80-d007-11e8-905e-8e2a94e9b45c.png">

At the same time, for my xmpp client status I get "offline". So it isn't actually connecting to the server or maintaining the connection.

This is my code: 

<img width="786" alt="capture d ecran 2018-10-14 a 23 21 20" src="https://user-images.githubusercontent.com/38508222/46922337-e4fe0000-d007-11e8-90c3-577ec0fdf843.png">

Hope someone has any clue about this. 

( by the way thank you, it is a really nice project and I hope I could help you in the future)

**Comment by sonnyp** [comment]
your service uri is wrong

use `xmpp://localhost:5222` or `localhost`

**Comment by mwmouawad** [comment]
Hey, thank you for the answer. So you are correct but I am still having another error. If I use service as you said with domain I get "no compatible connection method found". And if I use it with domain I get "Creating Url Js is not supported yet" (I know this is a React Native problem) I guess I should just find a way around without using URL to parse.

**Comment by sonnyp** [comment]
@mwmouawad fixed in https://github.com/xmppjs/xmpp.js/releases/tag/v0.5.1
