### ISSUE TITLE
Import server certificate alongside login

### ISSUE THREAD

**Issue by ukaric** [xmppjs/xmpp.js#575]
Hi, pardon for my gaps in knowledge of XMPP protocol but I'm looking into using this library with ReactNative to authorize application to Openfire server, but I need certificate that is issued by server to make secure connection is there an option or a way to provide certificate file alongside username and password ?

P.S Great job with the library structure is superb.

**Comment by sonnyp** [comment]
what kind of certificate? TLS or for SASL authentication?
