### ISSUE TITLE
domain.enter is not a function

### ISSUE THREAD

**Issue by tbto** [xmppjs/xmpp.js#582]
E:\Workspace\tbtosoft\projects\push-xmpp>node -v
v8.11.3

E:\Workspace\tbtosoft\projects\push-xmpp>node xmpp.js
(node:8116) UnhandledPromiseRejectionWarning: TypeError: domain.enter is not a function
    at Component.emit (events.js:199:12)
    at Component._status (E:\Workspace\tbtosoft\projects\push-xmpp\node_modules\@xmpp\connection\index.js:160:10)
    at promiseStart (E:\Workspace\tbtosoft\projects\push-xmpp\node_modules\@xmpp\connection\index.js:251:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:8116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8116) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tbto** [comment]
![image](https://user-images.githubusercontent.com/3437980/47333898-47fe2f80-d6b7-11e8-88fb-612dd29079c1.png)

**Comment by sonnyp** [comment]
which version of @xmpp/client are you using?

**Comment by david-j-lee** [comment]
I am getting the same issue when trying to connect via xmpp. I am using version 0.5.2

**Comment by sonnyp** [comment]
Ah got it, we only officially support Node.js 10 at the moment, I recommend upgrading.

**Comment by david-j-lee** [comment]
Upgrade to node 11 and can confirm that the error no longer appears.

**Comment by tbto** [comment]
Thanks all, I'm test in node 10 and node 11, it's ok.
