### ISSUE TITLE
What is the name of the npm corresponding to latest xmpp.js v0.52?

### ISSUE THREAD

**Issue by shubham1164** [xmppjs/xmpp.js#583]
I have used node-xmpp but it seems to be updated 2 years ago. I want to know if there is a new npm for the latest xmpp.js v0.52 (or atleast version greater than past 2 year) or I was looking at some wrong place. I want to embedd xmpp chat client in react-native by using xmpp.js. I apologize, if the question is silly but I am new to this. Thanks

**Comment by IllusionPerdu** [comment]
I think is : https://www.npmjs.com/package/xmpp.js (for all the packtage)
The client is here : https://www.npmjs.com/package/@xmpp/client
See here for all the individual package: https://www.npmjs.com/~sonny

**Comment by sonnyp** [comment]
@IllusionPerdu indeed, thanks.

@shubham1164  see https://github.com/xmppjs/xmpp.js/tree/master/packages/client
