### ISSUE TITLE
if the id of handlers is not get response in iq caller, what's happen next?

### ISSUE THREAD

**Issue by tbto** [xmppjs/xmpp.js#585]
It's will memory leak?

![image](https://user-images.githubusercontent.com/3437980/47546107-497f6000-d922-11e8-8208-0a0308f20b00.png)

**Comment by sonnyp** [comment]
`handlers.set` is a method on the [Map object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) not related to iq get/set
