### ISSUE TITLE
Install fails for reconnect-core

### ISSUE THREAD

**Issue by manniesah** [xmppjs/xmpp.js#589]
npm install fails for git repo of reconnect-core. Below is logs from verbose. 

`
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose' ]
npm info using npm@6.4.1
npm info using node@v10.13.0
npm verb npm-session e8d8fb28f2760661
npm info lifecycle helpdesk-chatbot@0.1.0~preinstall: helpdesk-chatbot@0.1.0
npm timing stage:loadCurrentTree Completed in 938ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 5ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 392ms
npm http fetch GET 200 http://<Internal Registry>:8081/repository/npm-public/node-xmpp-client 890ms
npm http fetch GET 200 http://<Internal Registry>:8081/repository/npm-public/browser-request 87ms
npm http fetch GET 200 http:/<Internal Registry>8081/repository/npm-public/md5.js 184ms
npm http fetch GET 200 http://<Internal Registry>:8081/repository/npm-public/minimist 236ms
npm http fetch GET 200 http://<Internal Registry>:8081/repository/npm-public/hash-base 75ms
npm http fetch GET 200 http://<Internal Registry>:8081/repository/npm-public/node-xmpp-core 270ms
npm http fetch GET 200 http://<Internal Registry>:8081/repository/npm-public/node-xmpp-tls-connect 87ms
npm http fetch GET 200 http://<Internal Registry>:8081/repository/npm-public/@xmpp%2fstreamparser 92ms
npm http fetch GET 200 http://<Internal Registry>.com:8081/repository/npm-public/@xmpp%2fjid 100ms
npm http fetch GET 200 http://<Internal Registry>:8081/repository/npm-public/lodash.assign 149ms
npm http fetch GET 200 http://<Internal Registry>:8081/repository/npm-public/ws 431ms
npm http fetch GET 200 http://<Internal Registry>:8081/repository/npm-public/@xmpp%2fxml 178ms
npm http fetch GET 200 http://<Internal Registry>:8081/repository/npm-public/options 79ms
npm http fetch GET 200 http://<Internal Registry>:8081/repository/npm-public/ultron 99ms
npm http fetch GET 200 http://<Internal Registry>:8081/repository/npm-public/ltx 235ms
npm http fetch GET 200 http://<Internal Registry>8081/repository/npm-public/ltx 176ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 9138ms
npm verb type system
npm verb stack FetchError: request to https://github.com/dodo/reconnect-core/tarball/merged failed, reason: connect ENETUNREACH 156.77.110.16:8080
npm verb stack     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
npm verb stack     at ClientRequest.emit (events.js:182:13)
npm verb stack     at onerror (/usr/local/lib/node_modules/npm/node_modules/agent-base/index.js:100:9)
npm verb stack     at callbackError (/usr/local/lib/node_modules/npm/node_modules/agent-base/index.js:122:5)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:68:7)
npm verb cwd /Users/sahmand/Documents/workspace/chatbot/chb00_chatbot
npm verb Darwin 17.7.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm verb node v10.13.0
npm verb npm  v6.4.1
npm ERR! code ENETUNREACH
npm ERR! errno ENETUNREACH
npm ERR! request to https://github.com/dodo/reconnect-core/tarball/merged failed, reason: connect ENETUNREACH 156.77.110.16:8080
npm verb exit [ 1, true ]
npm timing npm Completed in 9611ms

npm ERR! A complete log of this run can be found in:
npm ERR!     <User>.npm/_logs/2018-11-08T13_28_05_395Z-debug.log
`

**Comment by trampi** [comment]
Are you using some kind of proxy?

**Comment by manniesah** [comment]
yes

**Comment by trampi** [comment]
For me, that seems to be the problem.
Your proxy is not able to download the following file: https://github.com/dodo/reconnect-core/tarball/merged

I do not think that anyone here can do anything about that. Maybe you could ask the administrator of the proxy?

**Comment by manniesah** [comment]
i will check with my admin. would this also happen if i am going through internal registry?

**Comment by trampi** [comment]
Thats certainly possible if your registry uses the proxy.

**Comment by manniesah** [comment]
I got off the proxy and it worked. Thanks!

**Comment by trampi** [comment]
You're welcome :-)
