### ISSUE TITLE
importing xmpp.js 0.5.2 in angular results in async / await calls

### ISSUE THREAD

**Issue by trampi** [xmppjs/xmpp.js#590]
Hello,

I am maintaining a chat *library* in angular using xmpp.js targeting ES5. I've updated from xmpp.js 0.3.0 to 0.5.2 and now face the problem that the new version uses async / await. Unfortunately the build process of angular does not transpile the async/await calls of xmpp.js.

Here is the source of a sample application highlighting the problem:
https://raw.githubusercontent.com/trampi/angular-import-xmpp/
The build result can be viewed here:
https://raw.githubusercontent.com/trampi/angular-import-xmpp/master/dist/angular-import-xmpp/vendor.js

if you grep for `  async start() {` you will find:
```js
  /**
   * Opens the socket then opens the stream
   */
  async start() {
    if (this.status !== 'offline') {
      throw new Error('Connection is not offline')
    }

    const {service, domain, lang} = this.options

    await this.connect(service)

    const promiseOnline = promise(this, 'online')

    await this.open({domain, lang})

    return promiseOnline
  }
```
which comes from `@xmpp/connection/index.js`

Do you have any suggestions or ideas? In the best case, I do not want consumers of my library to have breaking changes. At the moment the library has a peer dependency on `@xmpp/client`, so that users of the library have to declare a dependency on `@xmpp/client` to prevent shipping it once in the library and once in the main app (e.g. if the main app also uses other functionality from xmpp.js).

Is changing the browser entrypoint in package.json to a babelified version a possible solution?

Thanks in advance,
Fabian

**Comment by sonnyp** [comment]
Hello @trampi 

Your project includes TypeScript, all you need is to tell TypeScript to compile xmpp.js. In my opinion it is not xmpp.js responsibility to compile for targets your project require.

Look at TypeScript compiler option `--allowJs` and do not exclude `node_modules`. This will also work for any non ES5 library you might use in the future and will guarantee consistency.

**Comment by trampi** [comment]
Hi Sonny,

thank you for your response.
I understand that you suggest to fix the build. I tried to configure the TypeScript compiler as you suggested, but the result is the same. I got typescript to compile your library via `npx tsc -p tsconfig.app.json` in the src directory. The compiled output looks like this:
* out-tsc/app/src -> the compiled application
* out-tsc/app/node_modules/@xmpp -> the compiled xmpp files

However, the build process of angular does also involve webpack. As far as I understand, webpack is used in the angular build process for minification / concatenating the dependencies. The further build process seems to ignore the compiled output of your library and only uses the compiled project. Which leads me to the next problem: the webpack build is not trivially customizable.

I have raised a [question on stackoverflow](https://stackoverflow.com/questions/53260252/angular-app-with-dependency-on-library-using-async-await-does-not-get-built-prop) and asked in the angular IRC channel. Another option might be [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus) to customize the webpack configuration. Until I find a satisfactory solution, I will revert to version 0.3.0.

You probably would not want to merge a PR, where the async/await calls are translated to Promises, would you?

Do you have any ideas left?

Thank you for your time,
Fabian

**Comment by sonnyp** [comment]
@trampi as a temporary solution you could use `@xmpp/client/dist/xmpp.js`

**Comment by AnBauer** [comment]
Probably the fastest solution would be to 
1) include xmpp.min.js in your angular.json scripts - section (line 28)
`"scripts": [
              "node_modules/@xmpp/client/dist/xmpp.min.js"
            ]`
2) get the client reference from window in the app.component constructor
`const client = window['XMPP'].client;
    client({});`
3) remove `import { client } from '@xmpp/client'; `

A more sophisticated approach would be to have type definition for XMPP client, but the above also works.

**Comment by trampi** [comment]
Hello @sonnyp and @AnBauer,

I definitely plan to upgrade to the newest version, but at the moment I will stay at 0.3.0.  
Thank you both for your help, but my team needs other features done and the library works with 0.3.0, I would just have preferred to upgrade sooner than later.

> A more sophisticated approach would be to have type definition for XMPP client, but the above also works.
I started with the types necessary for our library here: https://github.com/pazznetwork/ngx-chat/tree/master/projects/pazznetwork/ngx-chat/src/manual_typings/%40xmpp
However, it is not very sophisticated or good enough for @types.

Thank you and have a nice day,
Fabian

**Comment by BendingBender** [comment]
@sonnyp What might actually help here is a dedicated browser build by utilizing the `browser` field in `package.json`.

Of course this complicates the build system because you'll have to build 2 different versions of the lib with different compiler settings. This might however streamline adoption of your lib for browser-based projects.

Not sure what you think about it. If you'd be interested in this topic, I'd might make a scratch implmenetation so tha twe have something to discuss about. What do you think?

**Comment by sonnyp** [comment]
@BendingBender that's not what the browser field is for. The browser field is used to provide a different entry point than index for browserify/webpack/...

We already use it and we already have a build system for browser, see `@xmpp/client/dist/xmpp.min.js`.

**Comment by BendingBender** [comment]
> We already use it and we already have a build system for browser, see `@xmpp/client/dist/xmpp.min.js`.

I didn't check this, my fault. It seems that you already transform `async`/`await` to promises. Nevermind.
