### ISSUE TITLE
how to login anonymous

### ISSUE THREAD

**Issue by tbto** [xmppjs/xmpp.js#593]
use @xmpp/client

**Comment by sonnyp** [comment]
@tbto just connect to a anonymous server and do not pass the username/password/credentials option to `@xmpp/client`

**Comment by tbto** [comment]
> @tbto just connect to a anonymous server and do not pass the username/password/credentials option to `@xmpp/client`

I use openfire as the XMPP server, but it's not work.
<img width="979" alt="image" src="https://user-images.githubusercontent.com/3437980/48692391-ceebec80-ec10-11e8-8284-30682d13451d.png">

**Comment by sonnyp** [comment]
the error is right there in your terminal, you are using a self signed certificate not accepted by Node.js, try `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'`

**Comment by tbto** [comment]
there is two mechanism(PLAIN and ANONYMOUS) from server, but @xmpp/sasl it's use PLAN as default. how to change it use ANONYMOUS?
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/3437980/48883981-5b8aea80-ee5d-11e8-91bb-a46df9d96b37.png">
