### ISSUE TITLE
How to register a user to openfire server by using xmpp.js 

### ISSUE THREAD

**Issue by jishaofeng89** [xmppjs/xmpp.js#599]
I have build an openfire server, but i don't know how to create a user account to server by using xmppjs, is there simple case for reference

**Comment by pc-magas** [comment]
On a similar case  (handling presenc stanzas and roster) I implemented the login on myself by calling the message handling functions into the callback function of the following callback: `xmpp.on('stanza')`

```
xmpp.on('stanza', (stanza) => {
    const messageString = stanza.toString();
    try {
      if (new RegExp('<iq\s*.*>\s*<bind xmlns="urn:ietf:params:xml:ns:xmpp-bind">.*<\/bind><\/iq>').test(messageString)) return;
      if (presenceReply(stanza, webContents) !== false) return;
      // eslint-disable-next-line no-useless-return
      if (handleRoster(stanza, webContents) !== false) return;
      if (pingReply(stanza) !== false) return;
      if (handleMessageStanza(stanza, webContents) !== false) return;
    } catch (e) {
      console.error('Stanza Processing', e.toString());
      console.error('Error Trace', e.stack);
    }
  });
```

In other words as fart the documentation says there's no some sort of plugin to support that.

**Comment by sonnyp** [comment]
There's no official support in the library (yet?).

Shouldn't be too hard to do https://xmpp.org/extensions/xep-0389.html

**Comment by sonnyp** [comment]
closing in favor of https://github.com/xmppjs/xmpp.js/issues/783
