### ISSUE TITLE
packages deleted ( commit cb849a5 )

### ISSUE THREAD

**Issue by jjrh** [xmppjs/xmpp.js#611]
https://github.com/xmppjs/xmpp.js/commit/cb849a53901a5896f8f65428cc0177776b23ff21 

So I see all this stuff got deleted - what's the grand plan for non core functionality? To have a XMPP core package then a bunch of middleware / plugins so you can just include the XEP's you need?

Just curious where things are going.

**Comment by sonnyp** [comment]
Hello @jjrh 

> To have a XMPP core package then a bunch of middleware / plugins so you can just include the XEP's you need?

That has always been the idea, everything is opt-in. 

Regarding the deletions, the plan is to solidify core features/apis and re-introduce those packages and more features then.
