### ISSUE TITLE
nest element in tagged-template

### ISSUE THREAD

**Issue by caijiang** [xmppjs/xmpp.js#612]
how can I make the code below works fine?
```javascript
// works fine
    console.log(
      xml`<message type="chat" from="foo@domain" to="bar@domain"><body>here</body></message>`
    );

    const body = xml`<body>here</body>`;
    // "TypeError: s.replace is not a function" kill me
    console.log(
      xml`<message type="chat" from="foo@domain" to="bar@domain">${body}</message>`
    );
```

I think This is a must for building a good architecture of an application.

**Comment by sonnyp** [comment]
tagged template is not officially supported by `@xmpp/xml`and I don't recommend using it because there is no escaping

if you really want to insist with tagged template please open the issue on https://github.com/xmppjs/ltx

**Comment by caijiang** [comment]
well, we have got another solution for this job; anyway, thank you very much for your reply & all hard work.
