### ISSUE TITLE
How to use scramsha1 auth instead of plain

### ISSUE THREAD

**Issue by git001** [xmppjs/xmpp.js#613]
There is the option to use the SCRAM-SHA-1 as auth mechanism.
I haven't seen any example or doc which shows the usage of this feature.

Please can you show me a snippet how I can use this auth method in the client, thanks.

**Comment by sonnyp** [comment]
SCRAM-SHA-1 is automatically negotiated however there was a bug making PLAIN the priority

Fixed in https://github.com/xmppjs/xmpp.js/releases/tag/v0.6.2

SCRAM-SHA-1 is now preferred over PLAIN
