### ISSUE TITLE
Feature Recomendation: Jquery-like child fetching on `@xmpp/xml` module.

### ISSUE THREAD

**Issue by pc-magas** [xmppjs/xmpp.js#618]
Sometimes in my application I woulg love if I could use more complex expressions to fetch children from a given xml object. Especially I would like if I could do stuff as the following examples are shown:

```
//Some XML Object
const body = xml('body', {}, xml('key', {type:'encryption'},'0xAFF1234DFA'), xml('key' , {type:'signature', '0xFFFA1234499908BCA'));

// encryptionKey would have value '0xAFF1234DFA'
const encryptionKey = body.getChild("key[type:'encryption']").text();
// signatureKey would have value '0xFFFA1234499908BCA'
const signatureKey = body.getChildText('key[type:\'signature\']');
``` 

With that I can query with less code given xml structures and stanzas.

**Comment by sonnyp** [comment]
feel free to use jQuery/DOM with your xml

I don't think this is worth having out of the box

**Comment by sonnyp** [comment]
BTW there is getChildByAttr

**Comment by pc-magas** [comment]
I cannot see any documentation for this method and how is used. I think it would be a good idea for the documentation to get updated offering documentation for this method.

**Comment by pc-magas** [comment]
If a code snippet provided here would be helpfull to me as well 0on how to use the `getChildByAttr`.

**Comment by sonnyp** [comment]
@pc-magas instead of documenting getChildByAttr which I think we will deprecate in the future I added example to use find and filter:

https://github.com/xmppjs/xmpp.js/tree/master/packages/xml#getchildren
