### ISSUE TITLE
Registering Custom stanza handling plugin/middleware.

### ISSUE THREAD

**Issue by pc-magas** [xmppjs/xmpp.js#619]
Sometimes I need to make my own XMPP extention or to register some code to handle the stanzas using a unified api so I can distribute them more easily. For example i would love if I could do:

```
const {client} = require('@xmpp/client');
const myMiddleWare = require('mycustomMiddleWare'); 
const anotherMiddelWare = require('anotherMiddleWare');
const yetAnotherMiddelWare = require('yetAnotherMiddelWare');

client = new Client();
client.registerMiddleware(myMiddleWare);
client.registerMiddleWare([anotherMiddelWare,yetAnotherMiddelWare]);
````

So I can have a unified API for handling the xmpp stanzas or even providing some custom authentication eg. XMPP on top of Websocket using OAUTH authentication.

**Comment by sonnyp** [comment]
you can already do this

https://github.com/xmppjs/xmpp.js/tree/master/packages/middleware
https://github.com/xmppjs/xmpp.js/tree/master/packages/iq#callee

```js
const {client} = require('@xmpp/client');
const xmpp = client(...)
const {middleware, iqCallee} = xmpp 
```
