### ISSUE TITLE
Update the XMPP logo

### ISSUE THREAD

**Issue by Neustradamus** [xmppjs/xmpp.js#626]
Can you update the XMPP logo?
The XMPP logo has been updated in 2017.

Source:
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

**Comment by sonnyp** [comment]
Where do we use the logo in this repository?

**Comment by sonnyp** [comment]
https://github.com/xmppjs done

the logo repository was archived

**Comment by Neustradamus** [comment]
@sonnyp: Can you update a last time?

There is a little change since...
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg
