### ISSUE TITLE
how to use plain auth when the XMPP server is support anonymous and plain mechanism

### ISSUE THREAD

**Issue by tbto** [xmppjs/xmpp.js#631]
I want use the plan auth instead of anonymous, but the XMPP sever can't disable the anonymous.
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/3437980/51878132-9a7f7400-23a9-11e9-83e1-5f5fb351f00e.png">

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/pull/633

**Comment by sonnyp** [comment]
fixed in [v0.7.0](https://github.com/xmppjs/xmpp.js/releases/tag/v0.7.0)
