### ISSUE TITLE
Getting could not parse error on stream element

### ISSUE THREAD

**Issue by gopal-abbineni** [xmppjs/xmpp.js#634]
Below is the message I am getting in the console when I am trying to establish XMPP connection using BOSH.

> could not parse<stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" version="1.0" id="******" from="******"> Error: Incomplete document
Socket.js:335
    at Parser.end

**Comment by gopal-abbineni** [comment]
when I tried to debug, this message is from C2S/BOSH/Socket.js -> respond function and there I found 
> // TODO, we need to filter the stream element

**Comment by gopal-abbineni** [comment]
Is there any update on this?

**Comment by sonnyp** [comment]
hello @gopal-abbineni 

Unfortunately I don't support node-xmpp anymore, but feel free to make a fix against the node-xmpp branch and I will make a fix release.
