### ISSUE TITLE
❌ TypeError: promise.finally is not a function

### ISSUE THREAD

**Issue by GRxRedZero** [xmppjs/xmpp.js#649]
Whats the Problem here?
------------------------------------------------------
Angular CLI: 7.3.8
Node: 8.10.0
OS: linux x64
Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.8 (cli-only)
@angular-devkit/core         7.3.8 (cli-only)
@angular-devkit/schematics   7.3.8 (cli-only)
@schematics/angular          7.3.8 (cli-only)
@schematics/update           0.13.8 (cli-only)
------------------------------------------------------

🛈 status connecting
🛈 status connect
🛈 status opening
⮊ <open version="1.0" xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="chatrix.de"/>
⮈ <open xmlns='urn:ietf:params:xml:ns:xmpp-framing' id='6730019600911100717' version='1.0' xml:lang='en' from='chatrix.de'/>
⮈ <stream:features xmlns:stream='http://etherx.jabber.org/streams'><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>DIGEST-MD5</mechanism><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>X-OAUTH2</mechanism></mechanisms><register xmlns='http://jabber.org/features/iq-register'/></stream:features>
⮊ <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="SCRAM-SHA-1">biwsbj1ncnhyZWR6ZXJvLHI9MmQ1ZWUyZWM2ZGE4OTI3YTAyNjQzNWMzYjFkOTIwYmY=</auth>
🛈 status open
⮈ <challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>cj0yZDVlZTJlYzZkYTg5MjdhMDI2NDM1YzNiMWQ5MjBiZnVHMC9GN1NoRDhRTkttV3FhdEY2TkE9PSxzPUVXZXhvaHQwN2VSZjhuUXlhMDl2cUE9PSxpPTQwOTY=</challenge>
⮊ <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="SCRAM-SHA-1">Yz1iaXdzLHI9MmQ1ZWUyZWM2ZGE4OTI3YTAyNjQzNWMzYjFkOTIwYmZ1RzAvRjdTaEQ4UU5LbVdxYXRGNk5BPT0scD0wT3JFdFZVQjlEc3FmdCtGN0x3MmtJQkdjTlE9</response>
⮈ <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>dj1CcnRqQ0ZhV0tvZzVxTmNIZjFGVUo0RU1UUVk9</success>
🛈 status opening
⮊ <open version="1.0" xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="chatrix.de"/>
⮈ <open xmlns='urn:ietf:params:xml:ns:xmpp-framing' id='15796711192192089911' version='1.0' xml:lang='en' from='chatrix.de'/>
🛈 status open
⮈ <stream:features xmlns:stream='http://etherx.jabber.org/streams'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/><session xmlns='urn:ietf:params:xml:ns:xmpp-session'><optional/></session><c ver='sg7ZnA5zzsPpRyrmVVRdsh4nhRU=' node='http://www.process-one.net/en/ejabberd/' hash='sha-1' xmlns='http://jabber.org/protocol/caps'/><sm xmlns='urn:xmpp:sm:2'/><sm xmlns='urn:xmpp:sm:3'/><csi xmlns='urn:xmpp:csi:0'/></stream:features>
⮊ <iq type="set" id="0b5x5swm8cy" xmlns="jabber:client"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>test</resource></bind></iq>
❌ TypeError: promise.finally is not a function
TypeError: promise.finally is not a function
    at timeout (/media/grxredzero/Ablagefestplatte/XMPP Chat/xmpp.js-master/node_modules/@xmpp/events/lib/timeout.js:14:20)
    at Object.request (/media/grxredzero/Ablagefestplatte/XMPP Chat/xmpp.js-master/node_modules/@xmpp/iq/caller.js:47:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
⮈ <iq xmlns='jabber:client' type='result' id='0b5x5swm8cy'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><jid>grxredzero@chatrix.de/test</jid></bind></iq>

**Comment by sonnyp** [comment]
what is your browser?

`promise.finally` is well supported https://caniuse.com/#search=promise.finally

You can use https://github.com/es-shims/Promise.prototype.finally

**Comment by sonnyp** [comment]
and if you're using Node.js, 8 is not supported, minimum requirement for xmpp.js is 10
