### ISSUE TITLE
Broken link on npmjs (How to use > 'examples')

### ISSUE THREAD

**Issue by synap5e** [xmppjs/xmpp.js#676]
The examples link (see below) on the [npmjs.com page](https://www.npmjs.com/package/node-xmpp-client) for this library points to https://github.com/node-xmpp/node-xmpp-client/tree/master/examples which results in a 404.

![image](https://user-images.githubusercontent.com/2515062/56947301-daa8eb00-6b80-11e9-9423-cab429825dba.png)

The github page on npmjs also points to node-xmpp/node-xmpp, although this redirects to the correct repository.

**Comment by sonnyp** [comment]
node-xmpp family is deprecated please refer to https://github.com/xmppjs/xmpp.js/tree/master/packages/client

**Comment by synap5e** [comment]
Is https://www.npmjs.com/package/node-xmpp-client not the correct place to get this library?
I am using `xmpp.js/packages/client/` in my project.

As far as I can see this repo was renamed but npm still points to the old repo name, although it is redirected by github.

**Comment by sonnyp** [comment]
the correct package for client is https://www.npmjs.com/package/@xmpp/client

**Comment by sonnyp** [comment]
I depracated node-xmpp packages family using npm deprecated.
