### ISSUE TITLE
Unable to use wss:// on React native in Android

### ISSUE THREAD

**Issue by shubham1164** [xmppjs/xmpp.js#680]
I am using react-native 0.59 with xmpp.js version 0.5.2

If I try to connect the chat server with ws:// protocol running on 5280, it works great
```
      xmpp = client({
        service:  'ws://localhost:5280/ws-xmpp',
        domain:   'localhost',
        resource: 'test',
        username: 'user1',
        password: 'pass1'
      });
      xmpp.start();
```

But If I try to connect with wss:// protocol running on 5285, it simply throws an error. 
```
      xmpp = client({
        service:  'wss://localhost:5285/ws-xmpp',
        domain:   'localhost',
        resource: 'test',
        username: 'user1',
        password: 'pass1'
      });
      xmpp.start();
```

Both (ws://)5280 and (wss://)5285 are working fine from the server point of view and has been verified by another web application which is using strophe.js

I want to ask is xmpp.js supports wss:// on react native? if yes, then is there anything else that I need to do to make it work?

**Comment by sonnyp** [comment]
> it simply throws an error.

What error?

I have used `wss://` with XMPP.js on React Native, should work. Is your server perhaps using an older version of the protocol?

**Comment by shubham1164** [comment]
This error is thrown on the server side:

08:31:29.899 [info] TLS server: In state certify received CLIENT ALERT: Fatal - Certificate Unknown

**Comment by shubham1164** [comment]
This works: 
'ws://localhost:5280/ws-xmpp'
This donot works. : 
'wss://localhost:5285/ws-xmpp'

But both the link works when I use strophe.js in another web application with the same config

**Comment by shubham1164** [comment]
The below is the config part of the Mongooseim chat server:
```
  %% BOSH and WS endpoints over HTTP
  { 5280, ejabberd_cowboy, [
      {num_acceptors, 10},
      {transport_options, [{max_connections, 1024}]},
      {modules, [
          {"_", "/http-bind", mod_bosh},
          {"_", "/ws-xmpp", mod_websockets, [
                                      {timeout, 60000},
                                      {ping_rate, 55000},
                                      {ejabberd_service, [
                                        {access, all},
                                        {shaper_rule, fast},
                                        {ip, {127, 0, 0, 1}},
                                        {password, "secret"}]}
          ]}
      ]}
  ]},

  %% BOSH and WS endpoints over HTTPS
  { 5285, ejabberd_cowboy, [
        {num_acceptors, 10},
        {transport_options, [{max_connections, 1024}]},
        {ssl, [{certfile, "priv/ssl/cert.pem"}, {keyfile, "priv/ssl/key.pem"}, {password, ""}]},
        {modules, [
            {"_", "/http-bind", mod_bosh},
            {"_", "/ws-xmpp", mod_websockets, [
                                        {timeout, 60000},
                                        {ping_rate, 55000},
                                        {ejabberd_service, [
                                          {access, all},
                                          {shaper_rule, fast},
                                          {ip, {127, 0, 0, 1}},
                                          {password, "secret"}]}
            ]}
        ]}
    ]},
```

**Comment by sonnyp** [comment]
what error client side?

**Comment by sonnyp** [comment]
try opening a websocket from RN:

```js
const ws = new WebSocket('wss://localhost:5285/ws-xmpp');

ws.onopen = () => {
  console.log('open')
};

ws.onmessage = (e) => {
  console.log(e.data);
};

ws.onerror = (e) => {
  console.log(e.message);
};

ws.onclose = (e) => {
  console.log(e.code, e.reason);
};
```

if it fails it's unrelated to xmpp.js

**Comment by sonnyp** [comment]
localhost won't work from your device, use the domain or ip address of your server

**Comment by shubham1164** [comment]
I am sure there must be something the domain part. Eg - Consider that I am using **example.com**, that points to my chat server ip address
Also, I have set up https on the example.com domain. Along with http://example.com will redirect to https://example.com

This works:
'ws://example.com:5280/ws-xmpp'
This donot works. :
'wss://example.com:5285/ws-xmpp'

Does it help?

**Comment by sonnyp** [comment]
try opening a websocket from RN:

```js
var ws = new WebSocket('ws://host.com/path');

ws.onopen = () => {
  // connection opened
  ws.send('something'); // send a message
};

ws.onmessage = (e) => {
  // a message was received
  console.log(e.data);
};

ws.onerror = (e) => {
  // an error occurred
  console.log(e.message);
};

ws.onclose = (e) => {
  // connection closed
  console.log(e.code, e.reason);
};
```

if it fails, it's unrelated to xmpp.js

**Comment by shubham1164** [comment]
How can I insert credentials like username and password in 
const ws = new WebSocket('wss://localhost:5285/ws-xmpp');

**Comment by sonnyp** [comment]
you don't, it is just about checking the connection can open

**Comment by shubham1164** [comment]
These are the actual credentials if you can help me in testing:

//this works
ws://colleapp.com:5280/ws-xmpp
user1@localhost
pass1

//this don't work
wss://colleapp.com:5285/ws-xmpp
user1@localhost
pass1

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/issues/680#issuecomment-489010898

come back with the result please

**Comment by shubham1164** [comment]
#680 (comment)
it is not connecting or giving any feedback

**Comment by shubham1164** [comment]
I will test it further, thanks for your time, I am removing the test info

**Comment by shubham1164** [comment]
By the time I am closing the issue, I have anything else, I will raise another issue. Thanks for support

**Comment by shubham1164** [comment]
I have observed that error is coming on Android only but working great on IOS with same code

**Comment by sonnyp** [comment]
Closing as unrelated to xmpp.js

Probably related to https://www.mrcodebot.com/2018/01/22/android-react-native-app-localhost-api/
