### ISSUE TITLE
React Native: Unable to resolve module

### ISSUE THREAD

**Issue by fecabianchi** [xmppjs/xmpp.js#685]
Hi,

I'm trying to use this lib, but facing the same issue as #572 

if i npm install tls, the error goes away but a new one appears: unable to resolve module `net` and keeps going, the last error i get was: unable to resolve module `randombytes`, This one i could not solve.

xmpp.js version: 0.7.1
React Native version: 0.48.4

Thanks!

**Comment by sonnyp** [comment]
Looks like your setup is trying to use the Node.js version. Do not install those extra dependencies.

Probably because you're using an "old" react native version.

Can you try import/require `@xmpp/client/browser` instead of `@xmpp/client` ?

**Comment by fecabianchi** [comment]
It worked!

Thank you @sonnyp. Can I add these instructions to the README?

**Comment by sonnyp** [comment]
@fecabianchi I'll take care of it because I would like to add a `@xmpp/client/react-native` file as well to make it less confusing

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/pull/717
