### ISSUE TITLE
Support for File transfer

### ISSUE THREAD

**Issue by rimzici** [xmppjs/xmpp.js#706]
Using [xmpp/client](https://github.com/xmppjs/xmpp.js/tree/master/packages/client). Please help me find any supported protocols for file transfer. I could not find much information about it. A related, but old [issue](https://github.com/xmppjs/xmpp.js/issues/247) seem to not help.

My actual requirement is in React-Native platform. I have tried two protocols in both React-Native as well as in Browser.

- [xep-0047](https://xmpp.org/extensions/xep-0047.html)

- [xep-0065](https://xmpp.org/extensions/xep-0065.html)

both the above seem to give an error in response.

```
<error type='cancel'>
    <service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
</error>
```

[here](https://github.com/rimzici/RN-XMPP-IBB) is a reproducible sample of react-native project trying xep-0047.

Thanks in advance!!

**Comment by rimzici** [comment]
I have also tried discovering the features/capabilities of the client defined by [xep-0030](https://xmpp.org/extensions/xep-0030.html). For this query also I get the same error response as above.

```
<error type="cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error>
```

So I assume this feature is also not supported?

**Comment by ggozad** [comment]
Hey @rimzici, xmpp.js does not (yet?) include support for most non-core protocols. It shouldn't be hard to add support to cover your needs. We did some work on protocols we needed for our own app [here](https://github.com/Crypho/xmpp-plugins) which perhaps can serve as an example on how to do your own.

**Comment by rimzici** [comment]
@ggozad  Thanks for the response. That is very helpful!!

**Comment by rimzici** [comment]
@ggozad inspired by your work, I gave an attempt to write a [plugin](https://github.com/telldus/xmppjs-client-plugins) of my own. May be I have not plugged in correctly.

For the IBB session requests that I make [here](https://github.com/telldus/xmppjs-client-plugins/blob/master/packages/xep-0047-ibb/index.js#L25), I still get the same above error.

```
<error type="cancel">
<service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
</error>
```

I expect [this method](https://github.com/telldus/xmppjs-client-plugins/blob/master/packages/xep-0047-ibb/index.js#L42) to respond for any incoming session request. For some reason it is not called.

May be I am missing something ? enable IBB namespace or any in the lib?

**Comment by sonnyp** [comment]
@rimzici I had a quick look at https://github.com/telldus/xmppjs-client-plugins/blob/master/packages/xep-0047-ibb/index.js#L42

You're missusing iq caller and iq callee.

* caller is to send iq requests (get and set) (think fetch/XMLHTTPRequest in the browser)
* callee is to respond to iq requests (think routes/middlewares in express/Node.js)

Instead of https://github.com/telldus/xmppjs-client-plugins/blob/master/packages/xep-0047-ibb/index.js#L118 you should do something **like**

```js
iqCallee.set('http://jabber.org/protocol/ibb', 'open', ctx => {
  // do stuff 
})
```

See https://github.com/xmppjs/xmpp.js/tree/master/packages/iq

Hope it helps.

**Comment by rimzici** [comment]
Thank you very much, that did help indeed!!

I have made changes as you have suggested [here](https://github.com/telldus/xmppjs-client-plugins/blob/master/packages/xep-0047-ibb/index.js#L28). With that now I am able to handle the incoming ibb requests.

An ambiguity that I am facing is, now I could see 2 responses for each request.

1. As expected the response from the [plugin](https://github.com/telldus/xmppjs-client-plugins/blob/master/packages/xep-0047-ibb/index.js#L52).

2. An error message with same `id`.

Here is a log.

![Screen Shot 2019-06-15 at 12 55 39 PM](https://user-images.githubusercontent.com/16771765/59548720-09342700-8f71-11e9-8174-0d7dc42da252.png)


1S: The expected response from "SI-file transfer" plugin, for SI request.

1E: Error response for the same SI  request.

**(Can see same `id` for 1S and 1E)**

2S: The expected response from "IBB" plugin, for IBB request.

2E: Error response for the same IBB  request.

**(Can see same `id` for 2S and 2E)**

Is it expected or is there anything that I could do to get rid of those error responses, once the plugin has handled the request?

**Comment by sonnyp** [comment]
@rimzici sorry the documentation isn't better.

I sent a PR that should fix your issues https://github.com/telldus/xmppjs-client-plugins/pull/1

**Comment by rimzici** [comment]
Thanks for the PR!!

I have checked and that seem to work perfectly, now I have better idea how to use `iqCallee`.

Thanks again :)
