### ISSUE TITLE
'offline' event not emitted correctly

### ISSUE THREAD

**Issue by pratikmoona** [xmppjs/xmpp.js#72]
``` javascript

var xmpp = require('node-xmpp');

var cl = new xmpp.Client({jid : JID, password : PASSWORD, host : HOST});

cl.on('online', function () {
    console.log("Came online");
    cl.send(new xmpp.Element('presence', { }).c('show').t('chat').up().c('st
atus').t('Online!!!'));
    this.end();
});

cl.on('offline', function () {
    console.log("Came offline");
});
```

This code when I run with valid credentials gives the following output
    Came online
and continues running. It never gets the 'offline' event as it should have. Any ways to resolve this?

**Comment by yuanchieh-cheng** [comment]
I run the example code.   
The online message showed up successfully.   
But when I close the wifi connection, the offline / disconnect / close event were not fired.  
How can I detect disconnect event ?
