### ISSUE TITLE
How to set the required SASL mechanism ?

### ISSUE THREAD

**Issue by harishgupta01** [xmppjs/xmpp.js#723]
Basically i was using node-xmpp-client which has something called way to select preferred SASL where i can opt for noauth but i dont see any option to set SASl mechanism in xmppjs client

**Comment by harishgupta01** [comment]
Basically i was using node-xmpp-client which has something called way to select preferred SASL where i can opt for noauth but i dont see any option to set SASl mechanism in xmppjs client

**Comment by sonnyp** [comment]
@harishgupta01 can you say more about what you want to achieve. Disabling SASL and use your own mechanism?

**Comment by harishgupta01** [comment]
Sorry for the confused heading. I was more looking if stream management xep is supported? Also a way to choose the SASL mechanism when connecting to socket ? e.g. I dont want to use any SASL, so will fake it by including a new SASL mechanism say 'NOAUTH' which i was doing in node-xmpp-client earlier.

**Comment by Doko-Demo-Doa** [comment]
I have the same question too. It seems that even if I don't set `username` and `password`, the client's mechanism is still treated as `PLAIN`

**Comment by sonnyp** [comment]
@harishgupta01 stream management is partially implemented https://github.com/xmppjs/xmpp.js/pull/580 but not released yet. It does not support ACK yet, I'll release ASAP.

**Comment by kriegster108** [comment]
I need to set my SASL to plain yet don’t have any way of doing this.. other npm packages for XMPP clients allow this functionality

**Comment by sonnyp** [comment]
duplicate https://github.com/xmppjs/xmpp.js/issues/808
