### ISSUE TITLE
Ionic 4  –Prod Mode stuck on white screen

### ISSUE THREAD

**Issue by Jayprakashsingh** [xmppjs/xmpp.js#737]
In Ionic v4, when I'm run app bundled in production mode (ionic cordova run android --prod), console says 'Could not find cordova.js script tag. Plugin loading may fail.' ,  
SyntaxError: Unexpected token async, remove plugin @xmppClient work perfect .
it should be installed and work as normal build.
Does anyone face this problem as well?
**ionic info**
```
Ionic:

   Ionic CLI                     : 5.2.2 (/Users/black/.nvm/versions/node/v10.15.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.1-dev.201905141607.d788a8e
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 12 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.1.2 (update available: 0.2.7)

System:

   ios-deploy : 1.9.2
   ios-sim    : 8.0.1
   NodeJS     : v10.15.3 (/Users/black/.nvm/versions/node/v10.15.3/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.2 Build version 10E125
```
**dependencies info**
"dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/device": "^5.8.0",
    "@ionic-native/file": "^5.8.0",
    "@ionic-native/geolocation": "^5.8.0",
    "@ionic-native/native-geocoder": "^5.8.0",
    "@ionic-native/network": "^5.8.0",
    "@ionic-native/social-sharing": "^5.9.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/sqlite": "^5.5.1",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic-native/toast": "^5.8.0",
    "@ionic/angular": "^4.4.1-dev.201905141607.d788a8e",
    "@ionic/core": "^4.4.1-dev.201905141607.d788a8e",
    "@ionic/storage": "^2.2.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@xmpp-plugins/pubsub": "^1.0.0",
    "@xmpp/client": "^0.7.4",
    "cordova-android": "8.0.0",
    "cordova-browser": "6.0.0",
    "cordova-ios": "5.0.1",
    "cordova-plugin-add-swift-support": "2.0.2",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-gaodelocation-chenyu": "2.0.2",
    "cordova-plugin-geolocation": "4.0.1",
    "cordova-plugin-nativegeocoder": "3.2.2",
    "cordova-plugin-network-information": "2.0.1",
    "cordova-plugin-x-socialsharing": "5.4.7",
    "cordova-plugin-x-toast": "2.7.2",
    "cordova-sqlite-storage": "3.2.0",
    "core-js": "^2.5.4",
    "crypto-js": "^3.1.9-1",
    "es6-promise-plugin": "4.2.2",
    "hammerjs": "^2.0.8",
    "rxjs": "~6.5.1",
    "shortid": "^2.2.14",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.29"
  }

**Comment by sonnyp** [comment]
https://github.com/ionic-team/ionic/issues/16437#issuecomment-441608238 ?

**Comment by Jayprakashsingh** [comment]
this is tsConfig file

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
```
all ready define  "target": "es5"

**Comment by sonnyp** [comment]
I really don't know about ionic sorry, maybe ask over there?
