### ISSUE TITLE
How to use @xmpp/xml analysis XML from server?

### ISSUE THREAD

**Issue by kipa-zhang** [xmppjs/xmpp.js#760]
How to use @xmpp/xml analysis XML from server?

Choose another one module?

@xmpp/xml  can only read msg  create by itself?

**Comment by sonnyp** [comment]
So you are trying to "read" an incomign XML stanza from the server?

See https://github.com/xmppjs/xmpp.js/tree/master/packages/xml#reading

```js
client.on('stanza', stanza => {
  console.log(stanza.getChild('body'))
});
```

**Comment by kipa-zhang** [comment]
Thanks very much!
