### ISSUE TITLE
How do I get the roster？

### ISSUE THREAD

**Issue by ptScaler** [xmppjs/xmpp.js#765]
How do I get the roster if I don't see the file related to the buddy list? The following does not return a result.
```
"@xmpp/client": "^0.7.4",
"react-native": "0.59.8",
```
```
const message1 = xml(
                'iq',
                { type: 'get', from: address, id: '17733914983989755905708', xmlns: 'jabber:iq:roster' }
            )
this.xmpp.send(message1)
```

**Comment by sonnyp** [comment]
use https://github.com/xmppjs/xmpp.js/tree/master/packages/iq#caller or https://github.com/Crypho/xmpp-plugins/tree/master/packages/roster
