### ISSUE TITLE
Unable to connect in React-Native

### ISSUE THREAD

**Issue by vjsingh96** [xmppjs/xmpp.js#772]
**Error**
`console.error."  ","Errror.WebSocket ECONNERROR ws://18.216.195.53:5280/ws-xmpp
`

**Configration**
 ```
const xmpp = client({
      service: 'ws://18.216.195.53:5280/ws-xmpp',
      domain: '18.216.195.53',
      resource: 'example',
      username: 'username',
      password: 'password',
    })
```

![WhatsApp Image 2019-09-01 at 1 11 03 AM](https://user-images.githubusercontent.com/25844227/64068412-7ba1d280-cc55-11e9-9bff-d93e7182667a.jpeg)

Please help me out

**Comment by sonnyp** [comment]
The error is pretty clear. Your phone cannot connect to that host. Not related to `xmpp.js`.
