### ISSUE TITLE
XML written in JSX format gives error

### ISSUE THREAD

**Issue by rahulchhabra07** [xmppjs/xmpp.js#774]
I am declaring XML in JSX format and getting a compilation error.

```
import React from 'react';

const {client, xml, jid} = require('@xmpp/client')

function SendPersonalMessage(xmpp, to, message_body) {
  const message = (
    <message type='chat' to={to}>
      <body>{message_body}</body>
    </message>
  )
  xmpp.send(message)
}

export default SendPersonalMessage

```

![WhatsApp Image 2019-09-19 at 10 21 41 AM](https://user-images.githubusercontent.com/9989778/65214376-64713a80-dac7-11e9-8cd7-7705cc8b4bab.jpeg)

**Comment by sonnyp** [comment]
try adding `/** @jsx xml */` at the begenning of the file and try again please

**Comment by rahulchhabra07** [comment]
This worked. Thanks!
