### ISSUE TITLE
No API to remove an iq callee route

### ISSUE THREAD

**Issue by wichert** [xmppjs/xmpp.js#779]
We used to be able to unregister an iq callee route like so:

```javascript
this.plugins['iq-callee'].setters.delete(xmlns)
```

This is no longer possible with the new middleware setup.

**Comment by wichert** [comment]
Some background here: we use that to only react to routes if certain React components are mounted.

**Comment by sonnyp** [comment]
Related https://github.com/xmppjs/xmpp.js/issues/643

XMPP being stateful, is is very unusual to dynamically remove handlers. Usually it's your handler that would decide whether to trigger actions/changes or not.

It is specially true for `iq` handlers as your application will change its contract "en route" and suddenly respond to them with a [`feature-not-implemented` error](https://xmpp.org/rfcs/rfc6120.html#stanzas-error-conditions-feature-not-implemented) and it does not play well with [Service Discovery](https://xmpp.org/extensions/xep-0030.html).

I believe it is a bad practice and would really advise against it, however I'm not totally against allowing it.

@wichert could you elaborate on the use case?

**Comment by sonnyp** [comment]
@wichert ping?

**Comment by wichert** [comment]
Sorry for the late response. Your argument makes a lot of sense. I've already refactored our code to always have the plugin running.
