### ISSUE TITLE
@xmpp/client/browser.js You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by unsilence** [xmppjs/xmpp.js#780]
webpack typescript React 

@xmpp/client/browser.js You may need an appropriate loader to handle this file type.

use:

import systemStore from '../store/SystemStore';
//先定义常量
// import { client, xml, jid } from '@xmpp/client';
const { client, xml, jid } = require('@xmpp/client');

export default class Xmpp {
    user: string = 'zxy';
    psw: string = 'password';
    service: string = '';
    resource: string = '';

    xmpp: any;

    constructor(_user: string, _psw: string, _service: string) {
        this.user = _user;
        this.psw = _psw;
        this.service = _service;
        this.resource = systemStore.resource;
        this.init();
    }

    init() {
        debugger;
        this.xmpp = client({
            service: `xmpp://${this.service}:5222`,
            resource: this.resource,
            username: this.user,
            password: this.psw,
        })
...
}

**Comment by sonnyp** [comment]
This is not an issue with xmpp.js .
Check your configuration.
