### ISSUE TITLE
Connection Opened Multiple Times

### ISSUE THREAD

**Issue by ShadowRanger** [xmppjs/xmpp.js#781]
So I am having a potential issue where my XMPP client is opening the connection multiple times. I doubt this is intentional, so I thought it would be worth creating an issue about it to confirm. Here is my code:
```
const username = "secret";
const password = "secret";
const client = client({
	service: host,
	resource: "origin",
	username: username,
	password: password
});
client.on("status", status => console.log(status));
client.on("error", error => {
	if (error.condition === "see-other-host") {
		const element = error.element.children[0];
		const child = element.children[0];

		client.options.service = `xmpp://${child}:5222`;
		client.options.domain = "chat.dm.origin.com";

		console.log("error - reconnecting");
	} else {
		console.log(error);
	}
});

try {
	await client.start();
} catch (error) {

}
```
The console output I am receiving is the following:
```
connecting
connect
opening
error - reconnecting
closing
close
open
disconnecting
disconnect
connecting
connect
opening
open
opening
open
opening
open
online
```
As you can see, the connection is opened multiple times towards the end.

**Comment by sonnyp** [comment]
`options` is private and not supposed to be used directly, it could be the issue.

Can you try the following:

`npm install @xmpp/debug`

```js
const username = "secret";
const password = "secret";
const client = client({
	service: host,
	resource: "origin",
	username: username,
	password: password
});
debug(client, true)
client.start().catch(console.error)
```

and share the output? (make sure you hide the SASL bits if you're using PLAIN mechanism)

**Comment by ShadowRanger** [comment]
@sonnyp I have gone ahead and tried out the code you provided. I had to terminate the application early with your exact code as it was stuck in a reconnect loop because it wasn't handling the see-other-host error like I originally did. I have gotten 2 sets of logs, 1 with your code and one with yours but with the added see-other-host error handling.

**Log 1 (No see-other-host error handling)**
https://gist.github.com/ShadowRanger/8224b8d9ff7f33b6b92d88ece5378d99

**Log 2 (Handling for see-other-host error)**
https://gist.github.com/ShadowRanger/7564f40ff83001e54d4fa986860f4afd

**Comment by sonnyp** [comment]
@ShadowRanger thanks. ok there are 2 issues

About `see-other-host`:

That's definitely something xmpp.js should implement. It's fairly easy to do if you want to give a try let me know, I'll be happy to help otherwise I can take care of it.

About the reconnect loop:

That's an expected behavior, via [`@xmpp/reconnect`](https://github.com/xmppjs/xmpp.js/tree/master/packages/reconnect).

Of course with an error like `see-other-host` it does not make much sense but once `see-other-host` is implemented it won't be an issue.

I'm wondering however if I should revisit the default behavior to only reconnect after a successful initial connection or prevent reconnect on specific stream errors. Let's address `see-other-host` and see.

**Comment by sonnyp** [comment]
For reference:

* https://xmpp.org/rfcs/rfc6120.html#streams-error-conditions-see-other-host
* https://github.com/xmppjs/xmpp.js/blob/master/packages/connection/index.js#L113 is where the error should be handled

**Comment by sonnyp** [comment]
Ok, there are some inter-dependencies with `reconnect` and `resolve` so I'm gonna implement this in a PR and you can give it a try if it works for you.

**Comment by ShadowRanger** [comment]
> Ok, there are some inter-dependencies with `reconnect` and `resolve` so I'm gonna implement this in a PR and you can give it a try if it works for you.

Alright no worries, will be happy to give it a try once ready.

**Comment by sonnyp** [comment]
Which `service` are you passing to `xmpp.js` so i can reproduce/test ?

**Comment by sonnyp** [comment]
ok I could reproduce with service `xmpp://chat.dm.origin.com`

however for some strange reason with service `chat.dm.origin.com` nothing seems to happen, I'll have a look into that too.

**Comment by ShadowRanger** [comment]
> ok I could reproduce with service `xmpp://chat.dm.origin.com`
> 
> however for some strange reason with service `chat.dm.origin.com` nothing seems to happen, I'll have a look into that too.

I can confirm that I am using `xmpp://chat.dm.origin.com`, apologies for not stating that. I tried without the xmpp, but it did not work either.

**Comment by sonnyp** [comment]
Okay there's a bit of an annoying issue with their servers. TLS is not configured correctly and when xmpp.js tries to connect it hangs.

I'm working on implementing `see-other-host`, I'll also give you a workaround for the TLS issue.

**Comment by ShadowRanger** [comment]
> Okay there's a bit of an annoying issue with their servers. TLS is not configured correctly and when xmpp.js tries to connect it hangs.
> 
> I'm working on implementing `see-other-host`, I'll also give you a workaround for the TLS issue.

Thank you very much for looking into this thoroughly and working on a solution. I will stay tuned for the changes!

**Comment by sonnyp** [comment]
@ShadowRanger looks like the server started replying with `This server does not serve chat.dm.origin.com` (after reconnecting to the `see-other-host`) but that did not happen half an hour ago. Do you know of an other origin/XMPP client that could you try and tell me if they're also having this issue?

**Comment by ShadowRanger** [comment]
> @ShadowRanger looks like the server started replying with `This server does not serve chat.dm.origin.com` (after reconnecting to the `see-other-host`) but that did not happen half an hour ago. Do you know of an other origin/XMPP client that could you try and tell me if they're also having this issue?
That is quite strange. I just tried connecting using my method in the error handler and I was able to connect without issues (still with the multiple connection open and closes though, but still works). I also tried using a Java XMPP client and that seems to work okay as well.

**Comment by sonnyp** [comment]
Could you share successful connection logs with `@xmpp/debug` again please?

**Comment by ShadowRanger** [comment]
@sonnyp The username is meant to be a user ID by the way, just in case you were testing using an Origin username. If you like, I can get your ID from your username if you like if you don't have it. Then you can use that for testing.

Here are the successful connection logs:
https://gist.github.com/ShadowRanger/7564f40ff83001e54d4fa986860f4afd

**Comment by sonnyp** [comment]
I guess my ip got blocked then. Maybe I made too many tries.

Anyway the PR is here: https://github.com/xmppjs/xmpp.js/pull/782

I have to go, I'll finish/merge/release later. Meanwhile you can fix the reconnect issue in your code with `client.reconnect.stop()` before calling `client.start`

**Comment by sonnyp** [comment]
Ok nevermind the issue with your code is a race condition, nothing you can do without the PR.

You can use 

```js
const xmpp = client({
  service: 'xmpp://0ada6961f53ef8124.gs.ea.com:5222',
  domain: 'chat.dm.origin.com',
  resource: 'example',
  username: 'username',
  password: 'password',
})
```

meanwhile

**Comment by ShadowRanger** [comment]
I have just had a try of the changes in the PR, and can confirm that it seems to work fine. However, I am still getting the multiple connections opened. Here are the logs:
https://gist.github.com/ShadowRanger/85bf1742b26ea29f1771e0f2a72e98e3

**Comment by sonnyp** [comment]
What makes you think you're getting multiple connections opened?

Multiple `open` and `connect` events are normal and part of the XMPP protocol. From the logs you sent, everything looks good.

**Comment by sonnyp** [comment]
Hmm actually no, you send 2 roster queries, not sure why. Could you share your code?

**Comment by ShadowRanger** [comment]
Just checked over my code and can see why I was fetching the roster twice. If the open events are normal, then all is well. I appreciate your fast responses to this issue and producing a solution to the see-other-host problem so fast. Thank you for all your help.
