### ISSUE TITLE
NPM Package Update

### ISSUE THREAD

**Issue by ShadowRanger** [xmppjs/xmpp.js#785]
Hello. Would you please be able to push the latest changes to NPM if possible? I have just reinstalled all of my dependencies and lost the manual changes I made from the see-other-host pull request I made. Thanks in advance.

**Comment by sonnyp** [comment]
I always try to release ASAP. If a change is not released yet it's because I haven't found the time to do so.

**Comment by sonnyp** [comment]
oops didn't mean to close this, will let you know here when it's done

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/releases/tag/v0.8.0
