### ISSUE TITLE
Detecting subscribed presences

### ISSUE THREAD

**Issue by ShadowRanger** [xmppjs/xmpp.js#789]
I tried my best to make sure that this was a valid thing to make an issue about before doing so, as per your advice on my last issue. I apologize if this ends up being something I overlooked.

So I am trying to detect when the client successfully accepts a subscription. I can confirm that the client is getting the subscribed presence as I can see it with the debug package running, but I am not sure how to listen for it as it is not sent through the stanza event.

This is the presence I am seeing in the debug logs:
`⮊ <presence type="subscribed" to="HIDDEN@chat.dm.origin.com"/>`

I am unsure how I can listen for this presence. Could you please let me know?

**Comment by sonnyp** [comment]
> I tried my best to make sure that this was a valid thing to make an issue about before doing so, as per your advice on my last issue. I apologize if this ends up being something I overlooked.

I appreciate, thanks.

`⮊` is that you send, not what you receive

BTW can you confirm this character `⮊` is a right arrow to you? I wonder if it renders differently.

If you don't get `⮈` (left arrow character) `presence` in your logs it probably is because you are not subscribed to presences. To do that, simply send a `presence` when online.

```js
xmp.on('online', () => {
  xmpp.send(xml('presence'))
})
```

**Comment by ShadowRanger** [comment]
@sonnyp I was using PowerShell to run my application and view the console output. Those icons don't seem to render there until I paste them into a text editor or here, which is why I didn't notice them until now that you have pointed them out. That makes sense now. All other presences seem to work fine, as I do make sure I send a presence once the client goes online. It was just the `subscribed` one that I thought I would receive a stanza for, but because I am sending it I am not able to which is understandable now. I think I will just listen for a roster update instead to determine if the subscription was successful (I check for an error stanza to handle if it failed). Thank you for clarifying this for me.

**Comment by sonnyp** [comment]
I'll replace those characters with 'IN' and 'OUT'.

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/pull/790
