### ISSUE TITLE
Is pubsub gone?

### ISSUE THREAD

**Issue by rgrunbla** [xmppjs/xmpp.js#791]
Hello,
looking at the commit history, I see that a pubsub plugin existed at some point. I cannot find it anymore; is it gone forevere or will it make a re-appearance at some point in the near/distant future?

Thanks,
Rémy

**Comment by ggozad** [comment]
Plugins are now gone from the core xmpp.js and are maintained separately. You will find the pubsub one [here](https://github.com/Crypho/xmpp-plugins)
