### ISSUE TITLE
websocket errors result in uncaught exceptions

### ISSUE THREAD

**Issue by wichert** [xmppjs/xmpp.js#797]
After enabling Sentry we are running into an unexpected error. If an XMPP server stops the following happens:

1. `Reconnect` tries to reconnect
1. This ends up calling `Client.connect` (from client-core).
1. This calls `Connection.connect`
1. Which calls `Socket.connect`
1. If this results in connection-refused the error handler from `Socket._attachSocket` is called. This does `this.emit('error', error)`
1. This runs the event handler from the `Connection._attachSocke`. This does `this.emit('error', error) itself.
1. Since there is no handler for the `error` event on the Connection instance EventEmitter will helpfully **throw an exception**
1. There is nothing to catch that exception, so Sentry catches it.
1. During development this results in the app blowing up and an error screen showing.

This is [document behaviour](https://nodejs.org/api/events.html#events_error_events) for EventEmitter, so we should handle this gracefully. I think the right approach for xmppjs is to wrap `this.emit('error', error)` in a try/catch.

**Comment by sonnyp** [comment]
The curent behavior is intented.

What's wrong with:

```js
client.on('error', err => {
  // error caught
})
```

?

**Comment by wichert** [comment]
Hm, is the client the same as the connection instance? If so that should indeed help.. this is probably a good thing to document as well.

**Comment by sonnyp** [comment]
> Hm, is the client the same as the connection instance?

yes

>  this is probably a good thing to document as well.

https://github.com/xmppjs/xmpp.js/tree/master/packages/client#event-error

    Emitted when an error occurs. For connection errors, xmpp will reconnect on its own using @xmpp/reconnect however a listener MUST be attached to avoid uncaught exceptions.

:)

**Comment by sonnyp** [comment]
@wichert beware `@xmpp/debug` does not play really well on react native because it uses `console.error` which triggers the red screen of death :p
