### ISSUE TITLE
[Question] How to run client?

### ISSUE THREAD

**Issue by dashingsuma** [xmppjs/xmpp.js#798]
My XMPP server is up and running I am using Openfire for the same.
I copied the given client given in example.js
Downloaded dependences, 
I am not getting what details should I enter : -

const XMPP = client({
  service: 'ws://localhost:5280/xmpp-websocket',
  domain: 'localhost',
  resource: 'example',
  username: 'username',
  password: 'password',
})

I am using this client as a node app.
Please, could anyone, guide me to make this run?

**Comment by sonnyp** [comment]
@dashingsuma can you please elaborate on what is not clear or self explanatory ?

did you see https://github.com/xmppjs/xmpp.js/tree/master/packages/client#client-1 ?
