### ISSUE TITLE
OMEMO Support?

### ISSUE THREAD

**Issue by chronikum** [xmppjs/xmpp.js#803]
Hello,

what are the possibilities of integrating OMEMO in this?

**Comment by sonnyp** [comment]
Infinite?

There is a third party implementation here https://github.com/telldus/xmppjs-client-plugins

**Comment by chronikum** [comment]
Thank you very much.

**Comment by timothyerwin** [comment]
I checked out that repo but it says the OMEMO is outdated. I’m having some difficulty trying to find a good example of how to connect to ejabberd with OMEMO in javascript.

I’ve checked out stanzajs (unclear if it implements omemo or just the protocol) conversejs headless (seems to lack documentation), and this library among others. Anyway have some pointers on what direction to take?

**Comment by Vardan-Uney** [comment]
@timothyerwin Found anything ?)
