### ISSUE TITLE
WebSocket ECONNERROR, trying to connect Prosody server with React-Native

### ISSUE THREAD

**Issue by turanmehmetb** [xmppjs/xmpp.js#804]
Hi im trying to connect my app with my prosody server which is running in an aws ec2 instance.
I have enabled mod_websocket in prosody, my prosody version is 0.11.3 and im trying to connect with something like this:
`const xmpp = client({
      service: 'ws://ec2-117-125-32-231.me-south-1.compute.amazonaws.com:5280/xmpp-websocket',
      domain: '',
      resource: '',
      username: 'mbt@ec2-117-125-32-231.me-south-1.compute.amazonaws.com',
      password: '12345678',
    });`

but i get the websocket econnerror, can someone help me with it? thanks!

**Comment by sonnyp** [comment]
Its not related to xmpp.is or react native.

Can you access http://ec2-117-125-32-231.me-south-1.compute.amazonaws.com:5280/xmpp-websocket with your browser? No. You need to find out why. Maybe you didn't restart prosody after enabling websocket or your firewall is not configured to allow 5280

**Comment by dca00** [comment]
Same issue here but with Openfire. Getting this in the console:

XMPP error WebSocket ECONNERROR wss://host.local.domain:7443/ws

I can go to that address/path in the same browser and see this:

> HTTP ERROR 405 HTTP method GET is not supported by this URL
> 
> URI: | /ws
> -- | --
> 405
> HTTP method GET is not supported by this URL
> org.jivesoftware.openfire.websocket.OpenfireWebSocketServlet-1c208136
