### ISSUE TITLE
@xmpp/component docs

### ISSUE THREAD

**Issue by toriqo** [xmppjs/xmpp.js#806]
How is this suppose to work? It always returns `<service-unavailable/>` event though I return a different stanza from `.on('stanza')`...

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/tree/master/packages/iq#callee

accessible via `component.iqCallee`

**Comment by toriqo** [comment]
thanks but no matter where i use
`
iqCallee.set('foo:bar', 'foo', (ctx) => {
        return xml('foo', {xmlns: 'foo:bar'})
    });
`
it doesn't change anything...

thanks

**Comment by toriqo** [comment]
nvm, solved it :) docs could be a little more detailed about it :)

**Comment by sonnyp** [comment]
Suggestions, or even better PR are welcome.
