### ISSUE TITLE
Update the XMPP logo to last perfect

### ISSUE THREAD

**Issue by Neustradamus** [xmppjs/xmpp.js#811]
There were 2 changes in the XMPP logo, please look here:
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

Old version, there was a problem: https://i.ibb.co/vcqmc8b/xmpp-logo-xsf-test.png

**Comment by sonnyp** [comment]
@Neustradamus do you know what is the font used in the logo?

**Comment by sonnyp** [comment]
see https://github.com/xmppjs/xmpp.js/pull/812/files?short_path=c4b0d0e#diff-c4b0d0e25e021c8acdd4f5d686ce68ea

**Comment by Neustradamus** [comment]
@sonnyp: Thanks :)
Have you found the font name?
