### ISSUE TITLE
How to add features?

### ISSUE THREAD

**Issue by joeygo** [xmppjs/xmpp.js#813]
Hello,

How can I add features?
I would like to register on pep for xmlns=http://jabber.org/protocol/geoloc+notify.
How can I achieve that?

Thank you

**Comment by joeygo** [comment]
Anyone? @sonnyp?

**Comment by joeygo** [comment]
The required XEPs are:
XEP-0163: Personal Eventing Protocol
XEP-0115: Entity Capabilities

Does xmpp.js or one of it's plugins supports those XEPs?

Thanks

**Comment by sonnyp** [comment]
@joeygo no but it should be trivial to do, look at the XEP example for what you want to do and use `client.send` for <presence/>` and `<message/>` and https://github.com/xmppjs/xmpp.js/tree/master/packages/iq#caller for `<iq/>`
