### ISSUE TITLE
Server?

### ISSUE THREAD

**Issue by brettz9** [xmppjs/xmpp.js#829]
Hi,

I'm seeing https://www.npmjs.com/package/node-xmpp-server redirect here (though the examples link is broken), I don't see that this package has any server functionality?

If you're hoping to add a server, maybe you could mention that on the README, and if not, maybe update the node-xmpp-server to mention its server functionality is deprecated?

Thanks!

**Comment by sonnyp** [comment]
> I'm seeing https://www.npmjs.com/package/node-xmpp-server redirect here (though the examples link is broken), I don't see that this package has any server functionality?

It doesn't, only its homepage url. One option would be to change it to https://github.com/xmppjs/xmpp.js/tree/node-xmpp/packages/node-xmpp-server

There was work started on server but it is nowhere near complete. https://github.com/xmppjs/xmpp.js/commit/56d610c2bb79a3546fa57fd45dc3b4332449c3a7

I'm not interested in adding noise to the README when it's already quite clear that server isn't implemented.
