### ISSUE TITLE
Issue while Implementing MUC logics

### ISSUE THREAD

**Issue by axcl** [xmppjs/xmpp.js#830]
Hey Guys,

Thanks for this amazing library. Actually i am facing ussing while implementing logics for MUC search, join etc.
Code:
`let _self = this;
        let message = xml(
            "iq",
            { xmlns: "jabber:client", type: "get", from: _self.address, id: 'get-room-info-0', to: 'conference.domain.com' },
            xml('query', 'http://jabber.org/protocol/disco#items')
        );
        let chatRoom = await this.xmppClient.iqCaller.get(message);
        console.log('Chat Rooms', chatRoom);`

Output XML:
`<iq 
type="get" 
from="test1user@domain.com/App59962" 
id="get-room-info-0'" 
to="conference.domain.com">
<query xmlns="http://jabber.org/protocol/disco#items"/>
</iq>`

Response:
`[Unhandled promise rejection: StanzaError: service-unavailable - No module is handling this query]
`

When i tried sending same xml from XMPP client gajim it worked and return disco items result.

Kindly help me out.

**Comment by axcl** [comment]
solved. Actually I have to use **this.xmppClient.iqCaller.request** instead of **this.xmppClient.iqCaller.get**

**Comment by sonnyp** [comment]
@axcl if you want to use `get` then remove the `iq` parent see https://github.com/xmppjs/xmpp.js/tree/master/packages/iq#get
