### ISSUE TITLE
cannot connecting to Openfire server frome Node.js

### ISSUE THREAD

**Issue by michelepapale1996** [xmppjs/xmpp.js#834]
Hi, 
I'm not unable to connecting to openfire server using this lib. I use the following code:

```
const { client, xml } = require("@xmpp/client");
const debug = require("@xmpp/debug");
let xmpp = client({
    service: "ws://192.168.0.16:5222/xmpp-websocket",
    domain: "192.168.0.16",
    username: "****",
    password: "****",
});

debug(xmpp, true);
```
In console:

<img width="504" alt="Schermata 2020-05-02 alle 12 38 31" src="https://user-images.githubusercontent.com/9197981/80861983-0407c580-8c72-11ea-8c14-58746763e0ce.png">

What is the problem? 

NB: I can correctly connect using Spark to the Openfire server.

**Comment by sonnyp** [comment]
https://stackoverflow.com/questions/34769824/what-does-this-error-mean-hpe-invalid-constant ?

**Comment by sonnyp** [comment]
Seems unrelated to xmpp.js, search the Web for `HPE_INVALID_CONSTANT`

**Comment by michelepapale1996** [comment]
Yes, you were right, it is not related to xmpp.js. My problems were:
- 5222 is not used for WebSockets protocol in OpenFire. To fix it, I used 7070. 
- the right endpoint is ws://192.168.0.16:7070/ws
