### ISSUE TITLE
cant fetch id sender

### ISSUE THREAD

**Issue by Updour** [xmppjs/xmpp.js#839]
I tried to receive messages from my friends, but I couldn't receive the sender's ID on my xmpp, but the message that was sent was already in my buddy, why is that ??
my code

https://pastebin.com/njYUsztD

**Comment by sonnyp** [comment]
you are not using xmpp.js and you know that because you already open a ticket on simple-xmpp

https://github.com/simple-xmpp/node-simple-xmpp/issues/90
