### ISSUE TITLE
Message receive event not found

### ISSUE THREAD

**Issue by akramkhan1102** [xmppjs/xmpp.js#852]
I can send messsage succefully but no such event was found so that I can receive the message

**Comment by sonnyp** [comment]
Do you send presence? If no; you won't receive message.

See https://github.com/xmppjs/xmpp.js/blob/master/packages/client/example.js

Closing as unrelated to xmpp.js

**Comment by akramkhan1102** [comment]
Got it, Thank you @sonnyp
