### ISSUE TITLE
XMPP Not connecting with live server

### ISSUE THREAD

**Issue by akramkhan1102** [xmppjs/xmpp.js#853]
I have succefully configuired XMPP server on my local and succesfully connected xmpp/client with localhot as well but not able to connect with live
When i connect @xmpp/client with ws://localhost:5280/ws-xmpp then status showing online and also message send to the registered user but when trying to connect same thing with live then first time status showing connecting and then disconnecting

**Comment by sonnyp** [comment]
I cannot provide support for your network or infrastructure.

Specially without any error or details whatsoever.

Feel free to comment if you have more details of how this is related to xmpp.js
