### ISSUE TITLE
Resource bind sends encoded bind

### ISSUE THREAD

**Issue by bees1** [xmppjs/xmpp.js#855]
On resource bind, the sent bind xmpp is encoded as a string within the iq tag.
Called in resource-binding/index.js (line 17).
Workaround was in iq/caller.js (_childRequest) changed from:
xml('iq', {type, to}, element)
to:
xml('iq', {type, to}, '').append(element)

**Comment by sonnyp** [comment]
Please reproduce the issue and share logs with https://github.com/xmppjs/xmpp.js/tree/master/packages/debug
