### ISSUE TITLE
XMPP Not connecting with live server

### ISSUE THREAD

**Issue by akramkhan1102** [xmppjs/xmpp.js#856]
I have susccefully configuired mongooseIM on my local and it's working fine on my app with local server, i can send message to the registerd client with local connection through webSocket and thet url is `ws://localhost:5280/ws-xmpp`
But it is **not working with live url** that is somthing like `ws://chat.example.com:5285/ws-xmpp` also i have tried with `wss` as there is SSL on live but that is not working as well 

When i am trying to connect client with local server then the connection status somthing like below screenshot
<img width="506" alt="Screenshot 2020-09-18 at 12 47 55 AM" src="https://user-images.githubusercontent.com/18122990/93518156-139a5900-f94a-11ea-976d-be6e6b1ad692.png">

When i am trying to connect client to the live server then the connection status like below screenshot
<img width="727" alt="Screenshot 2020-09-18 at 12 49 47 AM" src="https://user-images.githubusercontent.com/18122990/93518312-447a8e00-f94a-11ea-9b3f-593bffc8f389.png">

I have also enebeld websocket in my `.cfg` file as you can see below
```
{modules, [
           {"_", "/http-bind", mod_bosh},
           {"_", "/ws-xmpp", mod_websockets, [
           %% Uncomment to enable connection dropping or/and server-side pings
           %{timeout, 600000}, {ping_rate, 60000}
           ]}
           %% Uncomment to serve static files
           %{"_", "/static/[...]", cowboy_static,
           %  {dir, "/var/www", [{mimetypes, cow_mimetypes, all}]}
           %},
       ]}
```

Please let me know what i need to configure in my server `.cfg` file or do i need to add somthing with xmpp/client ?

**Comment by sonnyp** [comment]
`host-unknown` error means that you are not passing the right domain

see https://github.com/xmppjs/xmpp.js/tree/master/packages/client#client-1

**Comment by akramkhan1102** [comment]
Thank you @sonnyp , it's working now
