### ISSUE TITLE
Chat history

### ISSUE THREAD

**Issue by akramkhan1102** [xmppjs/xmpp.js#857]
Is there any event to get the chat history for users

**Comment by akramkhan1102** [comment]
can any one help me?

**Comment by jainrahil** [comment]
Yes, While Using with react native not able to get the history for chat, however in react js it can be done using strophe but for react native not able to fetch either using strophe or some libraries, somebody able to get any success using react native .?

**Comment by ravichauchan** [comment]
I am facing same issue...

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/issues/773

**Comment by Princejain21** [comment]
> Yes, While Using with react native not able to get the history for chat, however in react js it can be done using strophe but for react native not able to fetch either using strophe or some libraries, somebody able to get any success using react native .?

how did you resolve this in react?
