### ISSUE TITLE
Problem with IE11

### ISSUE THREAD

**Issue by dennisdahlc** [xmppjs/xmpp.js#859]
When I try to instantiate the Client, I get an error in IE11:
![image](https://user-images.githubusercontent.com/17319141/96240996-df927200-0fa1-11eb-9f43-4b564a627c5e.png)
I am using the latest version of Xmpp.js.

Am I missing something to make this work?

**Comment by sonnyp** [comment]
Well - what's the error?

What is your setup? How do you "use" xmpp.js ?
