### ISSUE TITLE
Is there support for Shared Roster Groups?

### ISSUE THREAD

**Issue by rahulchhabra07** [xmppjs/xmpp.js#867]
I am using xmpp.js along with Ejabberd. I created a shared roster group with multiple people. When they send presence, I see the logs on Ejabberd server, but don't receive them on the client. Is this a known issue? Can you help with what could possibly be wrong here?

Thanks.

**Comment by sonnyp** [comment]
Are you sending your presence? That's how you subscribe to others.

Regardless the issue is unrelated to xmpp.js itself - please get help from https://xmpp.org/community/
