### ISSUE TITLE
Module sends error type="cancel" <service-unavailable> after receiving content jingle from Xmpp server.

### ISSUE THREAD

**Issue by sowmya-subramaniam8** [xmppjs/xmpp.js#880]
Hi, 
We are trying to connect to our prosody server to fetch audio content for recording, after sending the presence we receive a jingle containing the xml for the audio content. The module then sends the following immediately after:
```
<iq type="error" xmlns="jabber:client">
    <jingle xmlns="urn:xmpp:jingle:1">
         <content name="audio"> 
             //rest of the jingle data
          </content>
     </jingle>
      <error type="cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error>
</iq>
```
Once this is sent, we get disconnected from the server in 2 minutes. Why is this sent? How can we keep our connection to the server alive?

**Comment by sonnyp** [comment]
Please share complete logs with https://github.com/xmppjs/xmpp.js/tree/master/packages/debug (feel free to redact sensitive or verbose data).

It doesn't look like it's related to xmpp.js though...
