### ISSUE TITLE
nothing showing up after "opening"

### ISSUE THREAD

**Issue by raj-862006** [xmppjs/xmpp.js#895]
i connected the client to ejabberd xmpp server 
in console it shows :
status connecting xmpps://localhost:5280/admin
connecting
server started 
status connect 
connect        
status opening 
opening        
and then nothing is showing up
what should i do?, is there an authentication error ?

**Comment by sonnyp** [comment]
Please fill the information from the bug template.

https://github.com/xmppjs/xmpp.js/issues/new?assignees=&labels=&template=bug-report.md&title=
