### ISSUE TITLE
support attach?

### ISSUE THREAD

**Issue by abelshare** [xmppjs/xmpp.js#900]
https://strophe.im/strophejs/doc/1.2.8/files/strophe-js.html#Strophe.Connection.attach

**Comment by sonnyp** [comment]
Please do some research before opening issues.

I already told you in https://github.com/xmppjs/xmpp.js/issues/896 that xmpp.js does not support http/bosh.

attach is a http/bosh feature only

https://github.com/xmppjs/xmpp.js/issues/561
