### ISSUE TITLE
XMPP Client that connects and works with Ejabberd

### ISSUE THREAD

**Issue by mayank-mundhra-2012** [xmppjs/xmpp.js#901]
**Is your feature request related to a problem? Please describe.**
Not sure if the XMPP connects and works with Ejabberd and its releases. If it is able to, it will be a major shot in the arm and help in building ReactJS and React Native (with Expo Go) client apps. This will increase the popularity of this project even further.    

**Describe the solution you'd like**
XMPP client to connect and work with Ejabberd and its releases
Compatibility with ReactJS and React Native (with Expo Go). 

**Additional context**
Protocols Supported by ejabberd: https://www.process-one.net/en/ejabberd/protocols/

**Comment by sonnyp** [comment]
xmpp.js works fine with ejabberd.

**Comment by mayank-mundhra-2012** [comment]
But does it support all protocols?

**Comment by sonnyp** [comment]
This is what xmpp.js implements https://github.com/xmppjs/xmpp.js/blob/master/protocols.md out of the box.
