### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by abelshare** [xmppjs/xmpp.js#907]
# Syntax error

## Environment  
62.0.3202.84  Chromium  from android

## contect
file:
node_modules\@xmpp\connection\index.js
row: 193
```js
// Report Error

try {
      el = await this.close();
    } catch {}
```
```js
// That's right.

try {
      el = await this.close();
    } catch (e) {}
```

look this https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/try...catch

**Comment by sonnyp** [comment]
The JavaScript syntax is valid, it's called optional catch binding https://2ality.com/2017/08/optional-catch-binding.html

Use babel or 

```
<script
  src="https://unpkg.com/@xmpp/client@VERSION/dist/xmpp.min.js"
  crossorigin
></script>
```
