### ISSUE TITLE
Create client accounts

### ISSUE THREAD

**Issue by gokul50** [xmppjs/xmpp.js#908]
Is there any way to create a new client account in openfire server via this library? Iam new to this library so I don't know much more about that's why. Can anyone please help me out in this?

And can we create groups and send messages to group members using this library ?

**Comment by sonnyp** [comment]
Duplicate of https://github.com/xmppjs/xmpp.js/issues/783

There is an issue template for a reason.

> ⚠ If you need help with XMPP itself, please visit https://xmpp.org/community/ instead.
