### ISSUE TITLE
Support XEP-0313: Message Archive Management

### ISSUE THREAD

**Issue by pravi** [xmppjs/xmpp.js#915]
**Is your feature request related to a problem? Please describe.**
Matrix bifrost bridge is using xmpp.js to implement matrix to xmpp bidirectional bridge but it lacks support for MAM https://github.com/matrix-org/matrix-bifrost/issues/64

This means people connecting from xmmp apps to matrix rooms via the bridge will not see any offline messages.

**Describe the solution you'd like**
If xmpp.js implements mam support that will make it possible to add this support in the matrix bridge.

**Additional context**
Matrix bifrost bridge allows bidirectional connections between any public matrix or xmpp rooms. Lack of MAM support is a big missing feature in this setup.

**Comment by sonnyp** [comment]
https://github.com/xmppjs/xmpp.js/issues/773
