### ISSUE TITLE
XEP-0156 _xmppconnect is vulnerable to MITM

### ISSUE THREAD

**Issue by moparisthebest** [xmppjs/xmpp.js#933]
Context: https://mail.jabber.org/pipermail/standards/2022-February/038759.html

Vulnerable code: https://github.com/xmppjs/xmpp.js/blob/63aecc49157980f6d68cc58605cf8a3fef664a2a/packages/resolve/lib/dns.js#L39

**Comment by sonnyp** [comment]
Thank you.
