### ISSUE TITLE
@xmpp/client@0.13.1  dependencies not found

### ISSUE THREAD

**Issue by obenhammou** [xmppjs/xmpp.js#937]
**Describe the bug**
i use the rainbow-node-sdk dependency which uses the @xmpp/client@0.13.1
but when npm install:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @xmpp/reconnect@^0.13.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@xmpp/client'
npm ERR! notarget

should @xmpp/reconnect be published with version 0.13.1 at lest ?
the same question for all @xmpp dependencies which still are in 0.13.0 versions in package.json file of @xmpp/client@0.13.1 ?

**Logs**
results of npm-consider:

 @xmpp/client@0.13.1                           │ 0 B  │ 3 days ago    │ Permissive    │ ISC                       │ @babel/cli@^7.16.0,                             │
│                                               │      │               │               │                           │ @babel/core@^7.16.5,                            │
│                                               │      │               │               │                           │ @babel/node@^7.16.5,                            │
│                                               │      │               │               │                           │ @babel/plugin-transform-react-jsx@^7.16.5,      │
│                                               │      │               │               │                           │ @xmpp/client-core@^0.13.1,                      │
│                                               │      │               │               │                           │ @xmpp/iq@^0.13.1,                               │
│                                               │      │               │               │                           │ @xmpp/middleware@^0.13.1,                       │
│                                               │      │               │               │                           │ @xmpp/reconnect@^0.13.1,                        │
│                                               │      │               │               │                           │ @xmpp/resolve@^0.13.1,                          │
│                                               │      │               │               │                           │ @xmpp/resource-binding@^0.13.1,                 │
│                                               │      │               │               │                           │ @xmpp/sasl@^0.13.1,                             │
│                                               │      │               │               │                           │ @xmpp/sasl-anonymous@^0.13.1,                   │
│                                               │      │               │               │                           │ @xmpp/sasl-plain@^0.13.1,                       │
│                                               │      │               │               │                           │ @xmpp/sasl-scram-sha-1@^0.13.1,                 │
│                                               │      │               │               │                           │ @xmpp/session-establishment@^0.13.1,            │
│                                               │      │               │               │                           │ @xmpp/starttls@^0.13.1,                         │
│                                               │      │               │               │                           │ @xmpp/stream-features@^0.13.1,                  │
│                                               │      │               │               │                           │ @xmpp/stream-management@^0.13.1,                │
│                                               │      │               │               │                           │ @xmpp/tcp@^0.13.1,                              │
│                                               │      │               │               │                           │ @xmpp/tls@^0.13.1,                              │
│                                               │      │               │               │                           │ @xmpp/websocket@^0.13.1,                        │
│                                               │      │               │               │                           │ babel-plugin-jsx-pragmatic@^1.0.2 

**Environment**
As much as possible information about the environment running xmpp.js

**Comment by sonnyp** [comment]
Should be fixed - please try again.

**Comment by obenhammou** [comment]
it's working now thanks very much!
could i know what was wrong if possible ?

**Comment by sonnyp** [comment]
The package new releases were not published.

**Comment by obenhammou** [comment]
Thanks
