### ISSUE TITLE
SASL negotiation fails if 'mechanisms' contains boundary white spaces

### ISSUE THREAD

**Issue by serge-medvedev** [xmppjs/xmpp.js#952]
https://github.com/xmppjs/xmpp.js/blob/63aecc49157980f6d68cc58605cf8a3fef664a2a/packages/sasl/index.js#L13

An error `el.text is not a function` is thrown if `mechanisms` stream feature contains boundary whitespaces, i.e. isn't minified.

**Comment by sonnyp** [comment]
Do you have an example of such `xml` ?

**Comment by serge-medvedev** [comment]
> Do you have an example of such `xml` ?

```
<stream:features>
    <mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-bind">


       <mechanism>PLAIN</mechanism>


    </mechanisms>
</stream:features>
```
